<?php
/**
 * This file is part of SinergiaCRM.
 * SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
 * Copyright (C) 2013 - 2023 SinergiaTIC Association
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
 */
// Prevents directly accessing this file from a web browser
if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

include_once "modules/stic_Advanced_Web_Forms/actions/coreActions.php";

/**
 * SaveRecordAction
 *
 * Action that manages saving a Data Block to the Database.
 */
class SaveRecordAction extends HookDataBlockActionDefinition {
    public function __construct() {
        $this->isActive = true;
        $this->isUserSelectable = false; // Users cannot select this action manually
        $this->isAutomatic = true;       // The action is automatically generated by the system
        $this->category = 'data';
        $this->baseLabel = 'LBL_SAVE_RECORD_ACTION';
    }

    /**
     * Executes the action, receiving the resolved and validated main data block.
     *
     * @param ExecutionContext $context The global context.
     * @param FormAction $actionConfig The action configuration.
     * @param DataBlockResolved $block The main data block, ready to be used.
     * @return ActionResult
     */
    public function executeWithBlock(ExecutionContext $context, FormAction $actionConfig, DataBlockResolved $block): ActionResult
    {
        $module = $block->dataBlock->module;
        $bean = null;
        $onDuplicateAction = null;

        // Duplicate detection logic
        $duplicateRules = $block->dataBlock->duplicate_detections ?? [];
        foreach ($duplicateRules as $rule) {
            $queryFields = [];
            $canSearch = true;

            // Build the search fields for this rule
            foreach ($rule->fields as $fieldName) {
                $fieldValue = $block->getFieldValue($fieldName)?->value;

                // If a field in the duplicate rule is empty, do not apply the rule
                // (Two persons cannot be the same if both have an empty email field)
                if ($fieldValue === null || $fieldValue === '') {
                    $canSearch = false;
                    break; // Move to the next rule
                }
                $queryFields[$fieldName] = $fieldValue;
            }

            // If the rule is valid and has fields, search for the bean
            if ($canSearch && !empty($queryFields)) {
                $tempBean = BeanFactory::newBean($module);
                $foundBean = $tempBean->retrieve_by_string_fields($queryFields);

                if ($foundBean !== null) {
                    $bean = $foundBean; // Duplicate found
                    $onDuplicateAction = $rule->on_duplicate;
                    break; // Stop searching, we found one
                }
            }
        }

        // Action Logic (Create or Handle Duplicate)
        $modificationType = null;
        if ($bean === null) {
            // No duplicate, create a new one
            $bean = BeanFactory::newBean($module);
            // Assign user if a default one is set
            if (!empty($context->defaultAssignedUserId)) {
                $bean->assigned_user_id = $context->defaultAssignedUserId;
            }
            // Fill all bean fields
            $this->populateBean($bean, $block); 
            $bean->save();
            $modificationType = BeanModificationType::CREATED;

        } else {
            // Duplicate found, apply the rule
            switch ($onDuplicateAction) {
                case OnDuplicateAction::ERROR:
                    // Generate an error and stop the flow
                    return new ActionResult(ResultStatus::ERROR, $actionConfig, "Duplicate record found for module {$module}.");

                case OnDuplicateAction::UPDATE:
                    // Overwrite all fields of the existing bean
                    $this->populateBean($bean, $block);
                    $bean->save();
                    $modificationType = BeanModificationType::UPDATED;
                    break;

                case OnDuplicateAction::ENRICH:
                    // Fill only empty fields of the existing bean
                    $this->enrichBean($bean, $block); 
                    $bean->save();
                    $modificationType = BeanModificationType::ENRICHED;
                    break;
                
                case OnDuplicateAction::SKIP:
                default:
                    // Do nothing, the bean remains as it was
                    $modificationType = BeanModificationType::SKIPPED;
                    break;
            }
        }

        // Logging and Return
        $actionResult = new ActionResult(ResultStatus::OK, $actionConfig);
        
        // Register the modification (or non-modification)
        $actionResult->registerBeanModificationFromBlock($bean, $block, $modificationType);

        return $actionResult;
    }

    /**
     * Fills a bean with all form data (overwrites).
     */
    private function populateBean(SugarBean $bean, DataBlockResolved $block): void
    {
        foreach ($block->formData as $fieldName => $field) {
            if ($field != null) {
                $fieldDef = $bean->field_defs[$fieldName] ?? null;
                if ($fieldDef && isset($fieldDef['type']) && $fieldDef['type'] === 'relate' && !empty($fieldDef['id_name'])) {
                    // Relate field: we need to assign the related ID to the hidden ID field
                    $idField = $fieldDef['id_name'];
                    $bean->{$idField} = $field->value;
                } else {
                    $bean->{$fieldName} = $field->value;
                }
            }
        }
    }

    /**
     * Fills a bean only with empty fields (enriches).
     */
    private function enrichBean(SugarBean $bean, DataBlockResolved $block): void
    {
        foreach ($block->formData as $fieldName => $field) {
            // Check if the field in the bean is empty or null
            $isEmpty = ($bean->{$fieldName} === null || $bean->{$fieldName} === '');
            $fieldDef = $bean->field_defs[$fieldName] ?? null;

            // If it is a relate, check the related ID field
            if ($fieldDef && isset($fieldDef['type']) && $fieldDef['type'] === 'relate' && !empty($fieldDef['id_name'])) {
                $idField = $fieldDef['id_name'];
                $isEmpty = empty($bean->$idField);
            }

            if ($isEmpty) {
                if ($fieldDef && isset($fieldDef['type']) && $fieldDef['type'] === 'relate' && !empty($fieldDef['id_name'])) {
                    // Relate field: we need to assign the related ID to the hidden ID field
                    $idField = $fieldDef['id_name'];
                    $bean->{$idField} = $field->value;
                } else {
                    $bean->{$fieldName} = $field->value;
                }
            }
        }
    }
}
