<?php
$dictionary['adrep_menu_link'] = array(
    'table' => 'adrep_menu_link',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array (
  'report_id' => 
  array (
    'required' => false,
    'name' => 'report_id',
    'vname' => 'LBL_REPORT_NAME_ADREP_REPORT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'report_name' => 
  array (
    'required' => true,
    'source' => 'non-db',
    'name' => 'report_name',
    'vname' => 'LBL_REPORT_NAME',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Report this parameter is for.',
    'help' => 'Report this parameter is for.',
    'importable' => 'false',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'report_id',
    'ext2' => 'adrep_report',
    'module' => 'adrep_report',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'name' => 
  array (
    'name' => 'name',
    'vname' => 'LBL_NAME',
    'type' => 'name',
    'link' => true,
    'dbType' => 'varchar',
    'len' => '255',
    'unified_search' => false,
    'full_text_search' => 
    array (
      'boost' => 3,
    ),
    'required' => true,
    'importable' => 'required',
    'duplicate_merge' => 'disabled',
    'merge_filter' => 'disabled',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'size' => '20',
  ),
  'menu_module' => 
  array (
    'required' => true,
    'name' => 'menu_module',
    'vname' => 'LBL_MENU_MODULE',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'moduleList',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'menu_view' => 
  array (
    'required' => true,
    'name' => 'menu_view',
    'vname' => 'LBL_MENU_VIEW',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'adrep_menu_view_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'date_range' => 
  array (
    'required' => true,
    'name' => 'date_range',
    'vname' => 'LBL_DATE_RANGE',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'na',
    'no_default' => false,
    'comments' => 'Date range to automatically pass to the report',
    'help' => 'Date range to automatically pass to the report',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'adrep_date_range_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'id_parameter' => 
  array (
    'required' => true,
    'name' => 'id_parameter',
    'vname' => 'LBL_ID_PARAMETER',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'na',
    'no_default' => false,
    'comments' => 'Which paramter to fill with the passed record id',
    'help' => 'Which paramter to fill with the passed record id',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'adrep_id_parameter_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'from_date_paramter' => 
  array (
    'required' => true,
    'name' => 'from_date_paramter',
    'vname' => 'LBL_FROM_DATE_PARAMTER',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'na',
    'no_default' => false,
    'comments' => 'Which paramter to fill with the passed from date',
    'help' => 'Which paramter to fill with the passed from date',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'adrep_date_parameter_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'to_date_parameter' => 
  array (
    'required' => true,
    'name' => 'to_date_parameter',
    'vname' => 'LBL_TO_DATE_PARAMETER',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'na',
    'no_default' => false,
    'comments' => 'Which paramter to fill with the passed to date',
    'help' => 'Which paramter to fill with the passed to date',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'adrep_date_parameter_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'additional_parameters' => 
  array (
    'required' => false,
    'name' => 'additional_parameters',
    'vname' => 'LBL_ADDITIONAL_PARAMETERS',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Addisional parameters to pass in url format (param1=value&param2=value)',
    'help' => 'Addisional parameters to pass in url format (param1=value&amp;param2=value)',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'active_flag' => 
  array (
    'required' => false,
    'name' => 'active_flag',
    'vname' => 'LBL_ACTIVE_FLAG',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'run_flag' => 
  array (
    'required' => false,
    'name' => 'run_flag',
    'vname' => 'LBL_RUN_FLAG',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '1',
    'no_default' => false,
    'comments' => 'Should the report run directly without prompting the user to change the parameters',
    'help' => 'Should the report run directly without prompting the user to change the parameters',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'format' => 
  array (
    'required' => false,
    'name' => 'format',
    'vname' => 'LBL_FORMAT',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'view',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'adrep_format_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('adrep_menu_link', 'adrep_menu_link', array('basic','assignable','security_groups'));
