<?php
/**
* This file is part of SinergiaCRM.
* SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
* Copyright (C) 2013 - 2023 SinergiaTIC Association
*
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.
*
* You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
*/

$dictionary['stic_Signatures'] = array(
    'table' => 'stic_signatures',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'status' => array(
            'required' => true,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'open',
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_signatures_status_list',
            'studio' => 'visible',
            'dependency' => false,
            'popupHelp' => 'LBL_STATUS_HELP',
        ),
        'main_module' => array(
            'required' => false,
            'name' => 'main_module',
            'vname' => 'LBL_MAIN_MODULE',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => 'The primary module from which the signature process is initiated.',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'moduleList',
            'studio' => 'visible',
            'dependency' => false,
            'popupHelp' => 'LBL_MAIN_MODULE_HELP',
        ),
        'signer_path' => array(
            'required' => false,
            'name' => 'signer_path',
            'vname' => 'LBL_SIGNER_PATH',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => false,
            'options' => 'stic_signatures_signer_path_list',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'popupHelp' => 'LBL_SIGNER_PATH_HELP',
        ),
        'auth_method' => array(
            'required' => true,
            'name' => 'auth_method',
            'vname' => 'LBL_AUTH_METHOD',
            'type' => 'enum',
            'massupdate' => '1',
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_signatures_auth_methods_list',
            'studio' => 'visible',
            'dependency' => false,
            'popupHelp' => 'LBL_AUTH_METHOD_HELP',
        ),
        'type' => array(
            'required' => true,
            'name' => 'type',
            'vname' => 'LBL_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_signatures_types_list',
            'default' => 'individual',
            'studio' => 'visible',
            'dependency' => false,
            'popupHelp' => 'LBL_TYPE_HELP',
            
        ),
        'signature_mode' => array(
            'required' => true,
            'name' => 'signature_mode',
            'vname' => 'LBL_SIGNATURE_MODE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_signatures_modes_list',
            'studio' => 'visible',
            'dependency' => false,
            'popupHelp' => 'LBL_SIGNATURE_MODE_HELP',
        ),
        'activation_date' => array(
            'required' => true,
            'name' => 'activation_date',
            'vname' => 'LBL_ACTIVATION_DATE',
            'type' => 'datetimecombo',
            'display_default' => 'now',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
            'popupHelp' => 'LBL_ACTIVATION_DATE_HELP',
            
        ),
        'expiration_date' => array(
            'required' => false,
            'name' => 'expiration_date',
            'vname' => 'LBL_EXPIRATION_DATE',
            'type' => 'datetimecombo',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
            'popupHelp' => 'LBL_EXPIRATION_DATE_HELP',
        ),
        'minimum_signatures' => array(
            'required' => true,
            'name' => 'minimum_signatures',
            'vname' => 'LBL_MINIMUM_SIGNATURES',
            'type' => 'int',
            'massupdate' => 0,
            'default' => '1',
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '1',
            'min' => false,
            'max' => false,
        ),
        'pdf_audit_page' => array(
            'required' => true,
            'name' => 'pdf_audit_page',
            'vname' => 'LBL_PDF_AUDIT_PAGE',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'default' => '',
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_boolean_list',
            'studio' => 'visible',
            'dependency' => false,
            'popupHelp' => 'LBL_PDF_AUDIT_PAGE_HELP',
        ),
        'end_date' => array(
            'required' => false,
            'name' => 'end_date',
            'vname' => 'LBL_END_DATE',
            'type' => 'datetimecombo',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
            'popupHelp' => 'LBL_END_DATE_HELP',
        ),
        'pdftemplate_id_c' => array(
            'required' => false,
            'name' => 'pdftemplate_id_c',
            'vname' => 'LBL_PDF_TEMPLATE_PDFTEMPLATE_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
        ),
        'pdf_template' => array(
            'required' => true,
            'source' => 'non-db',
            'name' => 'pdf_template',
            'vname' => 'LBL_PDF_TEMPLATE',
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'pdftemplate_id_c',
            'ext2' => 'AOS_PDF_Templates',
            'module' => 'AOS_PDF_Templates',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            'resetFieldInStudio' => 'true',
            'popupHelp' => 'LBL_PDF_TEMPLATE_HELP',
        ),
        'emailtemplate_id_c' => array(
            'required' => true,
            'name' => 'emailtemplate_id_c',
            'vname' => 'LBL_EMAIL_TEMPLATE',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'default' => '000005f1-2e4e-3b11-051f-68e3c9e70330',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
        ),
        'email_template' => array(
            'required' => true,
            'source' => 'non-db',
            'name' => 'email_template',
            'vname' => 'LBL_EMAIL_TEMPLATE',
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'emailtemplate_id_c',
            'ext2' => 'EmailTemplates',
            'module' => 'EmailTemplates',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            'resetFieldInStudio' => 'true',
            'popupHelp' => 'LBL_EMAIL_TEMPLATE_HELP',
        ),
        'emailtemplatesenddocument_id_c' => array(
            'required' => true,
            'name' => 'emailtemplatesenddocument_id_c',
            'vname' => 'LBL_EMAIL_TEMPLATE_SEND_DOCUMENT',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'default' => '000005f1-2e4e-3b11-051f-68e3c9e70331',
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
        ),
        'email_template_send_document' => array(
            'required' => true,
            'source' => 'non-db',
            'name' => 'email_template_send_document',
            'vname' => 'LBL_EMAIL_TEMPLATE_SEND_DOCUMENT',
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'emailtemplatesenddocument_id_c',
            'ext2' => 'EmailTemplates',
            'module' => 'EmailTemplates',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            'resetFieldInStudio' => 'true',
            'popupHelp' => 'LBL_EMAIL_TEMPLATE_SEND_DOCUMENT_HELP',
        ),
        'emailtemplateotp_id_c' => array(
            'required' => true,
            'name' => 'emailtemplateotp_id_c',
            'vname' => 'LBL_EMAIL_TEMPLATE_OTP',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'default' => '000005f1-2e4e-3b11-051f-68e3c9e70332',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
        ),
        'email_template_otp' => array(
            'required' => true,
            'source' => 'non-db',
            'name' => 'email_template_otp',
            'vname' => 'LBL_EMAIL_TEMPLATE_OTP',                
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'emailtemplateotp_id_c',
            'ext2' => 'EmailTemplates',
            'module' => 'EmailTemplates',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            'resetFieldInStudio' => 'true',
            'popupHelp' => 'LBL_EMAIL_TEMPLATE_OTP_HELP',
        ),
        'emailtemplateotpsms_id_c' => array(
            'required' => true,
            'name' => 'emailtemplateotpsms_id_c',
            'vname' => 'LBL_EMAIL_TEMPLATE_OTP_SMS',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'default' => '000005f1-2e4e-3b11-051f-68e3c9e70333',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
        ),
        'email_template_otp_sms' => array(
            'required' => true,
            'source' => 'non-db',
            'name' => 'email_template_otp_sms',
            'vname' => 'LBL_EMAIL_TEMPLATE_OTP_SMS',                
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'emailtemplateotpsms_id_c',
            'ext2' => 'EmailTemplates',
            'module' => 'EmailTemplates',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            'resetFieldInStudio' => 'true',
            'popupHelp' => 'LBL_EMAIL_TEMPLATE_OTP_SMS_HELP',
        ),
        



        'on_behalf_of' => array(
            'required' => true,
            'name' => 'on_behalf_of',
            'vname' => 'LBL_ON_BEHALF_OF',
            'type' => 'enum',
            'massupdate' => '1',
            'default' => '0',
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_signatures_on_behalf_of_list',
            'studio' => 'visible',
            'dependency' => false,
            'popupHelp' => 'LBL_ON_BEHALF_OF_HELP',
        ),
        'pdf_document' => array(
            'required' => false,
            'name' => 'pdf_document',
            'vname' => 'LBL_PDF_DOCUMENT',
            'type' => 'file',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 255,
            'size' => '20',
            'studio' => 'visible',
            'dbType' => 'varchar',
            'border' => '',
            'width' => '120',
            'height' => '',
        ),
        'stic_signatures_stic_signers' => array(
            'name' => 'stic_signatures_stic_signers',
            'type' => 'link',
            'relationship' => 'stic_signatures_stic_signers',
            'source' => 'non-db',
            'module' => 'stic_Signers',
            'bean_name' => 'stic_Signers',
            'side' => 'right',
            'vname' => 'LBL_STIC_SIGNATURES_STIC_SIGNERS_FROM_STIC_SIGNERS_TITLE',
        ),
        'stic_signatures_stic_signature_log' => array(
            'name' => 'stic_signatures_stic_signature_log',
            'type' => 'link',
            'relationship' => 'stic_signatures_stic_signature_log',
            'source' => 'non-db',
            'module' => 'stic_Signature_Log',
            'bean_name' => 'stic_Signature_Log',
            'side' => 'right',
            'vname' => 'LBL_STIC_SIGNATURES_STIC_SIGNATURE_LOG_FROM_STIC_SIGNATURE_LOG_TITLE',
        ),

    ),
    'relationships' => array(
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
);

if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('stic_Signatures', 'stic_Signatures', array('basic', 'assignable', 'security_groups'));

// Set special values for SuiteCRM base fields
$dictionary['stic_Signatures']['fields']['name']['required'] = false;
$dictionary['stic_Signatures']['fields']['description']['rows'] = '2';
