<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

$dictionary['stic_Signatures'] = array(
    'table' => 'stic_signatures',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'status' => array(
            'required' => true,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'draft',
            'no_default' => false,
            'comments' => '',
            'help' => 'Status of the signature process (Draft, In Progress, Complete, Expired)',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_signatures_status_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'main_module' => array(
            'required' => false,
            'name' => 'main_module',
            'vname' => 'LBL_MAIN_MODULE',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => 'The primary module from which the signature process is initiated.',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'moduleList',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'signer_path' => array(
            'required' => false,
            'name' => 'signer_path',
            'vname' => 'LBL_SIGNER_PATH',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Path to extract email addresses ot phone data for signers from the primary module.',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
        ),
        'body' => array(
            'required' => false,
            'name' => 'body',
            'vname' => 'LBL_BODY',
            'type' => 'text',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'studio' => 'visible',
            'rows' => '4',
            'cols' => '20',
        ),
        'header' => array(
            'required' => false,
            'name' => 'header',
            'vname' => 'LBL_HEADER',
            'type' => 'wysiwyg',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'HTML body for the header of the document.',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => 0,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'dbType' => 'text',
        ),
        'footer' => array(
            'required' => false,
            'name' => 'footer',
            'vname' => 'LBL_FOOTER',
            'type' => 'wysiwyg',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'HTML body for the footer of the document.',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => 0,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'dbType' => 'text',
        ),
        'auth_method' => array(
            'required' => true,
            'name' => 'auth_method',
            'vname' => 'LBL_AUTH_METHOD',
            'type' => 'enum',
            'massupdate' => '1',
            'default' => 'unique_link',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_signatures_auth_methods_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'type' => array(
            'required' => true,
            'name' => 'type',
            'vname' => 'LBL_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_signatures_types_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'activation_date' => array(
            'required' => true,
            'name' => 'activation_date',
            'vname' => 'LBL_ACTIVATION_DATE',
            'type' => 'datetimecombo',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
            'display_default' => '+1 day&12:00am',
        ),
        'expiration_date' => array(
            'required' => false,
            'name' => 'expiration_date',
            'vname' => 'LBL_EXPIRATION_DATE',
            'type' => 'datetimecombo',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
        ),
        'minimum_signatures' => array(
            'required' => true,
            'name' => 'minimum_signatures',
            'vname' => 'LBL_MINIMUM_SIGNATURES',
            'type' => 'int',
            'massupdate' => 0,
            'default' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '1',
            'min' => false,
            'max' => false,
        ),
        'reminder_frequency' => array(
            'required' => false,
            'name' => 'reminder_frequency',
            'vname' => 'LBL_REMINDER_FREQUENCY',
            'type' => 'int',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '',
            'min' => false,
            'max' => false,
        ),
        'pdf_audit_page' => array(
            'required' => false,
            'name' => 'pdf_audit_page',
            'vname' => 'LBL_PDF_AUDIT_PAGE',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_boolean_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'generate_pdf' => array(
            'required' => true,
            'name' => 'generate_pdf',
            'vname' => 'LBL_GENERATE_PDF',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => 'Indicates whether a final PDF document should be generated.',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_boolean_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'end_date' => array(
            'required' => false,
            'name' => 'end_date',
            'vname' => 'LBL_END_DATE',
            'type' => 'datetimecombo',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Date and time when the signature process was completed.',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
        ),
        'verification_code' => array(
            'required' => false,
            'name' => 'verification_code',
            'vname' => 'LBL_VERIFICATION_CODE',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => 'Unique hash generated for the signed document for integrity verification.',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
        ),
        'margin_left' => array(
            'required' => false,
            'name' => 'margin_left',
            'vname' => 'LBL_MARGIN_LEFT',
            'type' => 'int',
            'massupdate' => '1',
            'default' => '15',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'len' => '255',
            'size' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '1',
            'no_default' => false,
            'inline_edit' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'min' => false,
            'max' => false,
        ),
        'margin_right' => array(
            'required' => false,
            'name' => 'margin_right',
            'vname' => 'LBL_MARGIN_RIGHT',
            'type' => 'int',
            'massupdate' => '1',
            'default' => '15',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'len' => '255',
            'size' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '1',
            'no_default' => false,
            'inline_edit' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'min' => false,
            'max' => false,
        ),
        'margin_top' => array(
            'required' => false,
            'name' => 'margin_top',
            'vname' => 'LBL_MARGIN_TOP',
            'type' => 'int',
            'massupdate' => '1',
            'default' => '16',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'len' => '255',
            'size' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '1',
            'no_default' => false,
            'inline_edit' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'min' => false,
            'max' => false,
        ),
        'margin_bottom' => array(
            'required' => false,
            'name' => 'margin_bottom',
            'vname' => 'LBL_MARGIN_BOTTOM',
            'type' => 'int',
            'massupdate' => '1',
            'default' => '16',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'len' => '255',
            'size' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '1',
            'no_default' => false,
            'inline_edit' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'min' => false,
            'max' => false,
        ),
        'margin_header' => array(
            'required' => false,
            'name' => 'margin_header',
            'vname' => 'LBL_MARGIN_HEADER',
            'type' => 'int',
            'massupdate' => '1',
            'default' => '9',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'len' => '255',
            'size' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '1',
            'no_default' => false,
            'inline_edit' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'min' => false,
            'max' => false,
        ),
        'margin_footer' => array(
            'required' => false,
            'name' => 'margin_footer',
            'vname' => 'LBL_MARGIN_FOOTER',
            'type' => 'int',
            'massupdate' => '1',
            'default' => '9',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'len' => '255',
            'size' => '20',
            'enable_range_search' => false,
            'disable_num_format' => '1',
            'no_default' => false,
            'inline_edit' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'min' => false,
            'max' => false,
        ),
        'page_size' => array(
            'required' => false,
            'name' => 'page_size',
            'vname' => 'LBL_PAGE_SIZE',
            'type' => 'enum',
            'massupdate' => '1',
            'default' => 'A4',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'len' => 100,
            'options' => 'pdf_page_size_dom',
            'studio' => 'visible',
            'no_default' => false,
            'inline_edit' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'dependency' => false,
        ),
        'orientation' => array(
            'required' => true,
            'name' => 'orientation',
            'vname' => 'LBL_ORIENTATION',
            'type' => 'enum',
            'massupdate' => '1',
            'default' => 'Portrait',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'len' => 100,
            'options' => 'pdf_orientation_dom',
            'studio' => 'visible',
            'no_default' => false,
            'inline_edit' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'dependency' => false,
        ),
        'emailtemplate_id_c' => array(
            'required' => false,
            'name' => 'emailtemplate_id_c',
            'vname' => 'LBL_EMAIL_TEMPLATE_EMAILTEMPLATE_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
        ),
        'email_template' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'email_template',
            'vname' => 'LBL_EMAIL_TEMPLATE',
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'emailtemplate_id_c',
            'ext2' => 'EmailTemplates',
            'module' => 'EmailTemplates',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            'resetFieldInStudio' => 'true',
        ),
        'on_behalf_of' => array(
            'required' => true,
            'name' => 'on_behalf_of',
            'vname' => 'LBL_ON_BEHALF_OF',
            'type' => 'enum',
            'massupdate' => '1',
            'default' => '0',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_boolean_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'pdf_document' => array(
            'required' => false,
            'name' => 'pdf_document',
            'vname' => 'LBL_PDF_DOCUMENT',
            'type' => 'file',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => '',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 255,
            'size' => '20',
            'studio' => 'visible',
            'dbType' => 'varchar',
            'border' => '',
            'width' => '120',
            'height' => '',
        ),
        'stic_signatures_stic_signers' => array(
            'name' => 'stic_signatures_stic_signers',
            'type' => 'link',
            'relationship' => 'stic_signatures_stic_signers',
            'source' => 'non-db',
            'module' => 'stic_Signers',
            'bean_name' => 'stic_Signers',
            'side' => 'right',
            'vname' => 'LBL_STIC_SIGNATURES_STIC_SIGNERS_FROM_STIC_SIGNERS_TITLE',
        ),
        'stic_signatures_stic_signature_log' => array(
            'name' => 'stic_signatures_stic_signature_log',
            'type' => 'link',
            'relationship' => 'stic_signatures_stic_signature_log',
            'source' => 'non-db',
            'module' => 'stic_Signature_Log',
            'bean_name' => 'stic_Signature_Log',
            'side' => 'right',
            'vname' => 'LBL_STIC_SIGNATURES_STIC_SIGNATURE_LOG_FROM_STIC_SIGNATURE_LOG_TITLE',
        ),

    ),
    'relationships' => array(
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('stic_Signatures', 'stic_Signatures', array('basic', 'assignable', 'security_groups'));
