<?php
$module_name = 'stic_Signers';
$listViewDefs[$module_name] =
array(
    'NAME' => array(
        'width' => '32%',
        'label' => 'LBL_NAME',
        'default' => true,
        'link' => true,
    ),
    'PARENT_NAME' => array(
        'type' => 'parent',
        'studio' => 'visible',
        'label' => 'LBL_FLEX_RELATE',
        'link' => true,
        'sortable' => false,
        'ACLTag' => 'PARENT',
        'dynamic_module' => 'PARENT_TYPE',
        'id' => 'PARENT_ID',
        'related_fields' => array(
            0 => 'parent_id',
            1 => 'parent_type',
        ),
        'width' => '10%',
        'default' => true,
    ),
    'STATUS' => array(
        'type' => 'enum',
        'default' => true,
        'studio' => 'visible',
        'label' => 'LBL_STATUS',
        'width' => '10%',
    ),
    'SIGNATURE_DATE' => array(
        'type' => 'datetimecombo',
        'label' => 'LBL_SIGNATURE_DATE',
        'width' => '10%',
        'default' => true,
    ),
    'STIC_SIGNATURES_STIC_SIGNERS_NAME' => array(
        'type' => 'relate',
        'link' => true,
        'label' => 'LBL_STIC_SIGNATURES_STIC_SIGNERS_FROM_STIC_SIGNATURES_TITLE',
        'id' => 'STIC_SIGNATURES_STIC_SIGNERSSTIC_SIGNATURES_IDA',
        'width' => '10%',
        'default' => true,
    ),
    'PHONE' => array(
        'type' => 'varchar',
        'label' => 'LBL_PHONE',
        'width' => '10%',
        'default' => true,
    ),
    'EMAIL_ADDRESS' => array(
        'type' => 'varchar',
        'label' => 'LBL_EMAIL_ADDRESS',
        'width' => '10%',
        'default' => true,
    ),
    'ASSIGNED_USER_NAME' => array(
        'width' => '9%',
        'label' => 'LBL_ASSIGNED_TO_NAME',
        'module' => 'Employees',
        'id' => 'ASSIGNED_USER_ID',
        'default' => true,
    ),
    'DATE_ENTERED' => array(
        'type' => 'datetime',
        'label' => 'LBL_DATE_ENTERED',
        'width' => '10%',
        'default' => true,
    ),
    'DATE_MODIFIED' => array(
        'type' => 'datetime',
        'label' => 'LBL_DATE_MODIFIED',
        'width' => '10%',
        'default' => true,
    ),
    'RECORD_ID' => array(
        'type' => 'varchar',
        'label' => 'LBL_RECORD_ID',
        'width' => '10%',
        'default' => false,
    ),
    'OTP' => array(
        'type' => 'varchar',
        'label' => 'LBL_OTP',
        'width' => '10%',
        'default' => false,
    ),
    'ON_BEHALF_OF_ID' => array(
        'type' => 'varchar',
        'label' => 'LBL_ON_BEHALF_OF_ID',
        'width' => '10%',
        'default' => false,
    ),
    'VERIFICATION_CODE' => array(
        'type' => 'varchar',
        'label' => 'LBL_VERIFICATION_CODE',
        'width' => '10%',
        'default' => false,
    ),
    'PDF_DOCUMENT' => array(
        'type' => 'image',
        'studio' => 'visible',
        'width' => '10%',
        'label' => 'LBL_PDF_DOCUMENT',
        'default' => false,
    ),
    'DESCRIPTION' => array(
        'type' => 'text',
        'label' => 'LBL_DESCRIPTION',
        'sortable' => false,
        'width' => '10%',
        'default' => false,
    ),
    'CREATED_BY_NAME' => array(
        'type' => 'relate',
        'link' => true,
        'label' => 'LBL_CREATED',
        'id' => 'CREATED_BY',
        'width' => '10%',
        'default' => false,
    ),
    'MODIFIED_BY_NAME' => array(
        'type' => 'relate',
        'link' => true,
        'label' => 'LBL_MODIFIED_NAME',
        'id' => 'MODIFIED_USER_ID',
        'width' => '10%',
        'default' => false,
    ),
    'OTP_EXPIRATION' => array(
        'type' => 'datetimecombo',
        'label' => 'LBL_OTP_EXPIRATION',
        'width' => '10%',
        'default' => false,
    ),
);
