<?php
$module_name = 'stic_Signers';
$searchdefs[$module_name] =
array(
    'layout' => array(
        'basic_search' => array(
            'name' => array(
                'name' => 'name',
                'default' => true,
                'width' => '10%',
            ),
            'parent_name' => array(
                'type' => 'parent',
                'studio' => 'visible',
                'label' => 'LBL_FLEX_RELATE',
                'link' => true,
                'sortable' => false,
                'ACLTag' => 'PARENT',
                'dynamic_module' => 'PARENT_TYPE',
                'id' => 'PARENT_ID',
                'related_fields' => array(
                    0 => 'parent_id',
                    1 => 'parent_type',
                ),
                'width' => '10%',
                'default' => true,
                'name' => 'parent_name',
            ),
            'status' => array(
                'type' => 'enum',
                'default' => true,
                'studio' => 'visible',
                'label' => 'LBL_STATUS',
                'width' => '10%',
                'name' => 'status',
            ),
            'signature_date' => array(
                'type' => 'datetimecombo',
                'label' => 'LBL_SIGNATURE_DATE',
                'width' => '10%',
                'default' => true,
                'name' => 'signature_date',
            ),
            'stic_signatures_stic_signers_name' => array(
                'type' => 'relate',
                'link' => true,
                'label' => 'LBL_STIC_SIGNATURES_STIC_SIGNERS_FROM_STIC_SIGNATURES_TITLE',
                'id' => 'STIC_SIGNATURES_STIC_SIGNERSSTIC_SIGNATURES_IDA',
                'width' => '10%',
                'default' => true,
                'name' => 'stic_signatures_stic_signers_name',
            ),
            'phone' => array(
                'type' => 'varchar',
                'label' => 'LBL_PHONE',
                'width' => '10%',
                'default' => true,
                'name' => 'phone',
            ),
            'email_address' => array(
                'type' => 'varchar',
                'label' => 'LBL_EMAIL_ADDRESS',
                'width' => '10%',
                'default' => true,
                'name' => 'email_address',
            ),
            'assigned_user_id' => array(
                'name' => 'assigned_user_id',
                'label' => 'LBL_ASSIGNED_TO',
                'type' => 'enum',
                'function' => array(
                    'name' => 'get_user_array',
                    'params' => array(
                        0 => false,
                    ),
                ),
                'width' => '10%',
                'default' => true,
            ),
            'current_user_only' => array(
                'name' => 'current_user_only',
                'label' => 'LBL_CURRENT_USER_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
        ),
        'advanced_search' => array(
            'name' => array(
                'name' => 'name',
                'default' => true,
                'width' => '10%',
            ),
            
            // Is not posible enable "parent_name" field in search layout
            // 'parent_name' => array(
            //     'type' => 'parent',
            //     'studio' => 'visible',
            //     'label' => 'LBL_FLEX_RELATE',
            //     'link' => true,
            //     'sortable' => false,
            //     'ACLTag' => 'PARENT',
            //     'dynamic_module' => 'PARENT_TYPE',
            //     'id' => 'PARENT_ID',
            //     'related_fields' => array(
            //         0 => 'parent_id',
            //         1 => 'parent_type',
            //     ),
            //     'width' => '10%',
            //     'default' => true,
            //     'name' => 'parent_name',
            // ),
            'status' => array(
                'type' => 'enum',
                'default' => true,
                'studio' => 'visible',
                'label' => 'LBL_STATUS',
                'width' => '10%',
                'name' => 'status',
            ),
            'signature_date' => array(
                'type' => 'datetimecombo',
                'label' => 'LBL_SIGNATURE_DATE',
                'width' => '10%',
                'default' => true,
                'name' => 'signature_date',
            ),
            'stic_signatures_stic_signers_name' => array(
                'type' => 'relate',
                'link' => true,
                'label' => 'LBL_STIC_SIGNATURES_STIC_SIGNERS_FROM_STIC_SIGNATURES_TITLE',
                'id' => 'STIC_SIGNATURES_STIC_SIGNERSSTIC_SIGNATURES_IDA',
                'width' => '10%',
                'default' => true,
                'name' => 'stic_signatures_stic_signers_name',
            ),
            'phone' => array(
                'type' => 'varchar',
                'label' => 'LBL_PHONE',
                'width' => '10%',
                'default' => true,
                'name' => 'phone',
            ),
            'email_address' => array(
                'type' => 'varchar',
                'label' => 'LBL_EMAIL_ADDRESS',
                'width' => '10%',
                'default' => true,
                'name' => 'email_address',
            ),
            'description' => array(
                'type' => 'text',
                'label' => 'LBL_DESCRIPTION',
                'sortable' => false,
                'width' => '10%',
                'default' => true,
                'name' => 'description',
            ),
            'date_entered' => array(
                'type' => 'datetime',
                'label' => 'LBL_DATE_ENTERED',
                'width' => '10%',
                'default' => true,
                'name' => 'date_entered',
            ),
            'on_behalf_of_id' => array(
                'type' => 'relate',
                'studio' => 'visible',
                'label' => 'LBL_ON_BEHALF_OF_ID',
                'id' => 'CONTACT_ID_C',
                'link' => true,
                'width' => '10%',
                'default' => true,
                'name' => 'on_behalf_of_id',
            ),
            'date_modified' => array(
                'type' => 'datetime',
                'label' => 'LBL_DATE_MODIFIED',
                'width' => '10%',
                'default' => true,
                'name' => 'date_modified',
            ),
            'modified_user_id' => array(
                'type' => 'assigned_user_name',
                'label' => 'LBL_MODIFIED',
                'width' => '10%',
                'default' => true,
                'name' => 'modified_user_id',
            ),
            'created_by' => array(
                'type' => 'assigned_user_name',
                'label' => 'LBL_CREATED',
                'width' => '10%',
                'default' => true,
                'name' => 'created_by',
            ),
            'assigned_user_id' => array(
                'name' => 'assigned_user_id',
                'label' => 'LBL_ASSIGNED_TO',
                'type' => 'enum',
                'function' => array(
                    'name' => 'get_user_array',
                    'params' => array(
                        0 => false,
                    ),
                ),
                'width' => '10%',
                'default' => true,
            ),
            'current_user_only' => array(
                'name' => 'current_user_only',
                'label' => 'LBL_CURRENT_USER_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
        ),
    ),
    'templateMeta' => array(
        'maxColumns' => '3',
        'maxColumnsBasic' => '4',
        'widths' => array(
            'label' => '10',
            'field' => '30',
        ),
    ),
);
