<?php

/**
 * Returns generated where SQL conditions from popup view. Fuction uses the $_REQUEST object generated by popup callback javascript function
 * 
 * The function is based in include/generic/Save2.php file, which contains the controller code for saving popup selection records when usin Select button in a "normal" subpanel throw SubPanelTopSelectButton widget.
 * 
 * @return String Generated where SQL conditions
 */
function generateAllWhereClausesFromGoalsPopup() {
    require_once 'include/formbase.php';

    // If the user selected "All records" from the selection menu, we pull up the list
    // based on the query they used on that popup to relate them to the parent record
    $order_by = '';
    $current_query_by_page = $_REQUEST['current_query_by_page'];
    $current_query_by_page_array = json_decode(html_entity_decode($current_query_by_page), true);

    $module = $current_query_by_page_array['module'];
    $seed = BeanFactory::getBean($module);
    if (empty($seed)) {
        sugar_die($GLOBALS['app_strings']['ERROR_NO_BEAN']);
    }
    $where_clauses = '';
    require_once 'include/SearchForm/SearchForm2.php';

    if (file_exists('custom/modules/' . $module . '/metadata/metafiles.php')) {
        require 'custom/modules/' . $module . '/metadata/metafiles.php';
    } elseif (file_exists('modules/' . $module . '/metadata/metafiles.php')) {
        require 'modules/' . $module . '/metadata/metafiles.php';
    }

    if (file_exists('custom/modules/' . $module . '/metadata/searchdefs.php')) {
        require_once 'custom/modules/' . $module . '/metadata/searchdefs.php';
    } elseif (!empty($metafiles[$module]['searchdefs'])) {
        require_once $metafiles[$module]['searchdefs'];
    } elseif (file_exists('modules/' . $module . '/metadata/searchdefs.php')) {
        require_once 'modules/' . $module . '/metadata/searchdefs.php';
    }

    if (!empty($metafiles[$module]['searchfields'])) {
        require_once $metafiles[$module]['searchfields'];
    } elseif (file_exists('modules/' . $module . '/metadata/SearchFields.php')) {
        require_once 'modules/' . $module . '/metadata/SearchFields.php';
    }
    if (!empty($searchdefs) && !empty($searchFields)) {
        $searchForm = new SearchForm($seed, $module);
        $searchForm->setup($searchdefs, $searchFields, 'SearchFormGeneric.tpl');
        $searchForm->populateFromArray($current_query_by_page_array, 'advanced');
        $where_clauses_arr = $searchForm->generateSearchWhere(true, $module);
        if (count($where_clauses_arr) > 0) {
            $where_clauses = '(' . implode(' ) AND ( ', $where_clauses_arr) . ')';
        }
    }

    return $where_clauses;

}
