<?php
// $module_name = 'stic_Payment_Commitments';
$subpanel_layout['list_fields'] = array(
    'name' => array(
        'vname' => 'LBL_NAME',
        'widget_class' => 'SubPanelDetailViewLink',
        'width' => '25%',
        'default' => true,
    ),
    'payment_type' => array(
        'type' => 'enum',
        'studio' => 'visible',
        'vname' => 'LBL_PAYMENT_TYPE',
        'width' => '10%',
        'default' => true,
    ),
    'payment_method' => array(
        'type' => 'enum',
        'studio' => 'visible',
        'vname' => 'LBL_PAYMENT_METHOD',
        'width' => '10%',
        'default' => true,
    ),
    'amount' => array(
        'type' => 'decimal',
        'align' => 'right',
        'vname' => 'LBL_AMOUNT',
        'width' => '10%',
        'default' => true,
    ),
    'first_payment_date' => array(
        'type' => 'date',
        'vname' => 'LBL_FIRST_PAYMENT_DATE',
        'width' => '10%',
        'default' => true,
    ),
    'end_date' => array(
        'type' => 'date',
        'vname' => 'LBL_END_DATE',
        'width' => '10%',
        'default' => true,
    ),
    'active' => array(
        'type' => 'boolean',
        'vname' => 'LBL_ACTIVE',
        'width' => '10%',
        'default' => true,
    ),
    'periodicity' => array(
        'type' => 'enum',
        'studio' => 'visible',
        'vname' => 'LBL_PERIODICITY',
        'width' => '10%',
        'default' => true,
    ),
    'stic_payment_commitments_contacts_name' => array(
        'type' => 'relate',
        'link' => true,
        'vname' => 'LBL_STIC_PAYMENT_COMMITMENTS_CONTACTS_FROM_CONTACTS_TITLE',
        'id' => 'STIC_PAYMENT_COMMITMENTS_CONTACTSCONTACTS_IDA',
        'width' => '10%',
        'default' => true,
        'widget_class' => 'SubPanelDetailViewLink',
        'target_module' => 'Contacts',
        'target_record_key' => 'stic_payment_commitments_contactscontacts_ida',
    ),
    'stic_payment_commitments_accounts_name' => array(
        'type' => 'relate',
        'link' => true,
        'vname' => 'LBL_STIC_PAYMENT_COMMITMENTS_ACCOUNTS_FROM_ACCOUNTS_TITLE',
        'id' => 'STIC_PAYMENT_COMMITMENTS_ACCOUNTSACCOUNTS_IDA',
        'width' => '10%',
        'default' => true,
        'widget_class' => 'SubPanelDetailViewLink',
        'target_module' => 'Accounts',
        'target_record_key' => 'stic_payment_commitments_accountsaccounts_ida',
    ),
    'assigned_user_name' => array(
        'link' => true,
        'type' => 'relate',
        'vname' => 'LBL_ASSIGNED_TO_NAME',
        'id' => 'ASSIGNED_USER_ID',
        'width' => '10%',
        'default' => true,
        'widget_class' => 'SubPanelDetailViewLink',
        'target_module' => 'Users',
        'target_record_key' => 'assigned_user_id',
    ),
    'edit_button' => array(
        'vname' => 'LBL_EDIT_BUTTON',
        'widget_class' => 'SubPanelEditButton',
        'module' => 'stic_Payment_Commitments',
        'width' => '4%',
        'default' => true,
    ),
    'remove_button' => array(
        // 'vname' => 'LBL_REMOVE',
        // 'widget_class' => 'SubPanelRemoveButton',
        // 'module' => 'stic_Payment_Commitments',
        // 'width' => '5%',
        // 'default' => true,
    ),
);
