<?php
// created: 2020-07-04 10:28:56
$searchdefs['Schedulers'] = array(
    'templateMeta' => array(
        'maxColumns' => '3',
        'widths' => array(
            'label' => '10',
            'field' => '30',
        ),
        'maxColumnsBasic' => '3',
    ),
    'layout' => array(
        'basic_search' => array(
            0 => array(
                'name' => 'name',
                'default' => true,
                'width' => '10%',
            ),
            1 => array(
                'type' => 'varchar',
                'label' => 'LBL_JOB',
                'width' => '10%',
                'default' => true,
                'name' => 'job',
            ),
            2 => array(
                'type' => 'enum',
                'label' => 'LBL_STATUS',
                'width' => '10%',
                'default' => true,
                'name' => 'status',
            ),
            3 => array(
                'type' => 'datetimecombo',
                'label' => 'LBL_DATE_TIME_START',
                'width' => '10%',
                'default' => true,
                'name' => 'date_time_start',
            ),
            4 => array(
                'type' => 'datetime',
                'label' => 'LBL_LAST_RUN',
                'width' => '10%',
                'default' => true,
                'name' => 'last_run',
            ),
            5 => array(
                'name' => 'favorites_only',
                'label' => 'LBL_FAVORITES_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
        ),
        'advanced_search' => array(
            0 => array(
                'type' => 'varchar',
                'label' => 'LBL_NAME',
                'name' => 'name',
                'default' => true,
                'width' => '10%',
            ),
            1 => array(
                'type' => 'varchar',
                'label' => 'LBL_JOB',
                'width' => '10%',
                'default' => true,
                'name' => 'job',
            ),
            2 => array(
                'type' => 'enum',
                'label' => 'LBL_STATUS',
                'width' => '10%',
                'default' => true,
                'name' => 'status',
            ),
            3 => array(
                'type' => 'datetimecombo',
                'label' => 'LBL_DATE_TIME_START',
                'width' => '10%',
                'default' => true,
                'name' => 'date_time_start',
            ),
            4 => array(
                'type' => 'datetimecombo',
                'label' => 'LBL_DATE_TIME_END',
                'width' => '10%',
                'default' => true,
                'name' => 'date_time_end',
            ),
            5 => array(
                'type' => 'datetime',
                'label' => 'LBL_LAST_RUN',
                'width' => '10%',
                'default' => true,
                'name' => 'last_run',
            ),
            6 => array(
                'type' => 'assigned_user_name',
                'label' => 'LBL_CREATED',
                'width' => '10%',
                'default' => true,
                'name' => 'created_by',
            ),
            7 => array(
                'type' => 'datetime',
                'label' => 'LBL_DATE_ENTERED',
                'width' => '10%',
                'default' => true,
                'name' => 'date_entered',
            ),
            8 => array(
                'type' => 'assigned_user_name',
                'label' => 'LBL_MODIFIED',
                'width' => '10%',
                'default' => true,
                'name' => 'modified_user_id',
            ),
            9 => array(
                'type' => 'datetime',
                'label' => 'LBL_DATE_MODIFIED',
                'width' => '10%',
                'default' => true,
                'name' => 'date_modified',
            ),
            10 => array(
                'type' => 'bool',
                'default' => true,
                'label' => 'LBL_CATCH_UP',
                'width' => '10%',
                'name' => 'catch_up',
            ),
            11 => array(
                'name' => 'favorites_only',
                'label' => 'LBL_FAVORITES_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
        ),
    ),
);