<?php
$module_name = 'stic_Signature_Log';
$searchdefs[$module_name] =
array(
    'layout' => array(
        'basic_search' => array(
            'name' => array(
                'name' => 'name',
                'default' => true,
                'width' => '10%',
            ),
            'date' => array(
                'type' => 'datetimecombo',
                'label' => 'LBL_DATE',
                'width' => '10%',
                'default' => true,
                'name' => 'date',
            ),
            'action' => array(
                'type' => 'enum',
                'default' => true,
                'label' => 'LBL_ACTION',
                'width' => '10%',
                'name' => 'action',
            ),
            'description' => array(
                'type' => 'text',
                'label' => 'LBL_DESCRIPTION',
                'sortable' => false,
                'width' => '10%',
                'default' => true,
                'name' => 'description',
            ),
            'stic_signers_stic_signature_log_name' => array(
                'type' => 'relate',
                'link' => true,
                'label' => 'LBL_STIC_SIGNERS_STIC_SIGNATURE_LOG_FROM_STIC_SIGNERS_TITLE',
                'id' => 'STIC_SIGNERS_STIC_SIGNATURE_LOGTIC_SIGNERS_IDA',
                'width' => '10%',
                'default' => true,
                'name' => 'stic_signers_stic_signature_log_name',
            ),
            'stic_signatures_stic_signature_log_name' => array(
                'type' => 'relate',
                'link' => true,
                'label' => 'LBL_STIC_SIGNATURES_STIC_SIGNATURE_LOG_FROM_STIC_SIGNATURES_TITLE',
                'id' => 'STIC_SIGNATURES_STIC_SIGNATURE_LOGTIC_SIGNATURES_IDA',
                'width' => '10%',
                'default' => true,
                'name' => 'stic_signatures_stic_signature_log_name',
            ),
            'ip_address' => array(
                'type' => 'varchar',
                'label' => 'LBL_IP_ADDRESS',
                'width' => '10%',
                'default' => true,
                'name' => 'ip_address',
            ),
            'user_agent' => array(
                'type' => 'varchar',
                'label' => 'LBL_USER_AGENT',
                'width' => '10%',
                'default' => true,
                'name' => 'user_agent',
            ),
            'assigned_user_id' => array(
                'name' => 'assigned_user_id',
                'label' => 'LBL_ASSIGNED_TO',
                'type' => 'enum',
                'function' => array(
                    'name' => 'get_user_array',
                    'params' => array(
                        0 => false,
                    ),
                ),
                'width' => '10%',
                'default' => true,
            ),
            'current_user_only' => array(
                'name' => 'current_user_only',
                'label' => 'LBL_CURRENT_USER_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
        ),
        'advanced_search' => array(
            'name' => array(
                'name' => 'name',
                'default' => true,
                'width' => '10%',
            ),
            'date' => array(
                'type' => 'datetimecombo',
                'label' => 'LBL_DATE',
                'width' => '10%',
                'default' => true,
                'name' => 'date',
            ),
            'action' => array(
                'type' => 'enum',
                'default' => true,
                'label' => 'LBL_ACTION',
                'width' => '10%',
                'name' => 'action',
            ),
            'description' => array(
                'type' => 'text',
                'label' => 'LBL_DESCRIPTION',
                'sortable' => false,
                'width' => '10%',
                'default' => true,
                'name' => 'description',
            ),
            'stic_signers_stic_signature_log_name' => array(
                'type' => 'relate',
                'link' => true,
                'label' => 'LBL_STIC_SIGNERS_STIC_SIGNATURE_LOG_FROM_STIC_SIGNERS_TITLE',
                'id' => 'STIC_SIGNERS_STIC_SIGNATURE_LOGTIC_SIGNERS_IDA',
                'width' => '10%',
                'default' => true,
                'name' => 'stic_signers_stic_signature_log_name',
            ),
            'stic_signatures_stic_signature_log_name' => array(
                'type' => 'relate',
                'link' => true,
                'label' => 'LBL_STIC_SIGNATURES_STIC_SIGNATURE_LOG_FROM_STIC_SIGNATURES_TITLE',
                'id' => 'STIC_SIGNATURES_STIC_SIGNATURE_LOGTIC_SIGNATURES_IDA',
                'width' => '10%',
                'default' => true,
                'name' => 'stic_signatures_stic_signature_log_name',
            ),
            'ip_address' => array(
                'type' => 'varchar',
                'label' => 'LBL_IP_ADDRESS',
                'width' => '10%',
                'default' => true,
                'name' => 'ip_address',
            ),
            'user_agent' => array(
                'type' => 'varchar',
                'label' => 'LBL_USER_AGENT',
                'width' => '10%',
                'default' => true,
                'name' => 'user_agent',
            ),
            'assigned_user_id' => array(
                'name' => 'assigned_user_id',
                'label' => 'LBL_ASSIGNED_TO',
                'type' => 'enum',
                'function' => array(
                    'name' => 'get_user_array',
                    'params' => array(
                        0 => false,
                    ),
                ),
                'width' => '10%',
                'default' => true,
            ),
            'date_entered' => array(
                'type' => 'datetime',
                'label' => 'LBL_DATE_ENTERED',
                'width' => '10%',
                'default' => true,
                'name' => 'date_entered',
            ),
            'date_modified' => array(
                'type' => 'datetime',
                'label' => 'LBL_DATE_MODIFIED',
                'width' => '10%',
                'default' => true,
                'name' => 'date_modified',
            ),
            'modified_user_id' => array(
                'type' => 'assigned_user_name',
                'label' => 'LBL_MODIFIED',
                'width' => '10%',
                'default' => true,
                'name' => 'modified_user_id',
            ),
            'created_by' => array(
                'type' => 'assigned_user_name',
                'label' => 'LBL_CREATED',
                'width' => '10%',
                'default' => true,
                'name' => 'created_by',
            ),
            'current_user_only' => array(
                'name' => 'current_user_only',
                'label' => 'LBL_CURRENT_USER_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
        ),
    ),
    'templateMeta' => array(
        'maxColumns' => '3',
        'maxColumnsBasic' => '4',
        'widths' => array(
            'label' => '10',
            'field' => '30',
        ),
    ),
);
