<?php
$dashletData['stic_AssetsDashlet']['searchFields'] = array(
    'date_entered' => array(
        'default' => '',
    ),
    'date_modified' => array(
        'default' => '',
    ),
    'stic_assets_contacts_name' => array(
        'default' => '',
    ),
    'code' => array(
        'default' => '',
    ),
    'type' => array(
        'default' => '',
    ),
    'assigned_user_name' => array(
        'default' => '',
    ),
    'assigned_user_id' => array(
        'default' => '',
    ),
);
$dashletData['stic_AssetsDashlet']['columns'] = array(
    'name' => array(
        'width' => '40%',
        'label' => 'LBL_LIST_NAME',
        'link' => true,
        'default' => true,
        'name' => 'name',
    ),
    'stic_assets_contacts_name' => array(
        'type' => 'relate',
        'link' => true,
        'label' => 'LBL_STIC_ASSETS_CONTACTS_FROM_CONTACTS_TITLE',
        'id' => 'STIC_ASSETS_CONTACTSCONTACTS_IDA',
        'width' => '10%',
        'default' => true,
    ),
    'code' => array(
        'type' => 'varchar',
        'label' => 'LBL_CODE',
        'width' => '10%',
        'default' => true,
    ),
    'type' => array(
        'type' => 'enum',
        'studio' => 'visible',
        'label' => 'LBL_TYPE',
        'width' => '10%',
        'default' => true,
    ),
    'start_date' => array(
        'type' => 'date',
        'label' => 'LBL_START_DATE',
        'width' => '10%',
        'default' => true,
    ),
    'date_entered' => array(
        'width' => '15%',
        'label' => 'LBL_DATE_ENTERED',
        'default' => true,
        'name' => 'date_entered',
    ),
    'phone' => array(
        'type' => 'relate',
        'studio' => 'visible',
        'label' => 'LBL_PHONE',
        'id' => 'ACCOUNT_ID5_C',
        'link' => true,
        'width' => '10%',
        'default' => false,
    ),
    'gas' => array(
        'type' => 'relate',
        'studio' => 'visible',
        'label' => 'LBL_GAS',
        'id' => 'ACCOUNT_ID3_C',
        'link' => true,
        'width' => '10%',
        'default' => false,
    ),
    'utilities_notes' => array(
        'type' => 'text',
        'studio' => 'visible',
        'label' => 'LBL_UTILITIES_NOTES',
        'sortable' => false,
        'width' => '10%',
        'default' => false,
    ),
    'security' => array(
        'type' => 'relate',
        'studio' => 'visible',
        'label' => 'LBL_SECURITY',
        'id' => 'ACCOUNT_ID6_C',
        'link' => true,
        'width' => '10%',
        'default' => false,
    ),
    'water' => array(
        'type' => 'relate',
        'studio' => 'visible',
        'label' => 'LBL_WATER',
        'id' => 'ACCOUNT_ID4_C',
        'link' => true,
        'width' => '10%',
        'default' => false,
    ),
    'electricity' => array(
        'type' => 'relate',
        'studio' => 'visible',
        'label' => 'LBL_ELECTRICITY',
        'id' => 'ACCOUNT_ID2_C',
        'link' => true,
        'width' => '10%',
        'default' => false,
    ),
    'insurance_notes' => array(
        'type' => 'text',
        'studio' => 'visible',
        'label' => 'LBL_INSURANCE_NOTES',
        'sortable' => false,
        'width' => '10%',
        'default' => false,
    ),
    'insured_contents' => array(
        'type' => 'enum',
        'studio' => 'visible',
        'label' => 'LBL_INSURED_CONTENTS',
        'width' => '10%',
        'default' => false,
    ),
    'insured_building' => array(
        'type' => 'enum',
        'studio' => 'visible',
        'label' => 'LBL_INSURED_BUILDING',
        'width' => '10%',
        'default' => false,
    ),
    'policy_number' => array(
        'type' => 'varchar',
        'label' => 'LBL_POLICY_NUMBER',
        'width' => '10%',
        'default' => false,
    ),
    'insurance' => array(
        'type' => 'relate',
        'studio' => 'visible',
        'label' => 'LBL_INSURANCE',
        'id' => 'ACCOUNT_ID1_C',
        'link' => true,
        'width' => '10%',
        'default' => false,
    ),
    'ownership_notes' => array(
        'type' => 'text',
        'studio' => 'visible',
        'label' => 'LBL_OWNERSHIP_NOTES',
        'sortable' => false,
        'width' => '10%',
        'default' => false,
    ),
    'key_set' => array(
        'type' => 'enum',
        'studio' => 'visible',
        'label' => 'LBL_KEY_SET',
        'width' => '10%',
        'default' => false,
    ),
    'owners_president' => array(
        'type' => 'relate',
        'studio' => 'visible',
        'label' => 'LBL_OWNERS_PRESIDENT',
        'id' => 'CONTACT_ID2_C',
        'link' => true,
        'width' => '10%',
        'default' => false,
    ),
    'ownership_percentage' => array(
        'type' => 'int',
        'default' => false,
        'label' => 'LBL_OWNERSHIP_PERCENTAGE',
        'width' => '10%',
    ),
    'estate_company' => array(
        'type' => 'relate',
        'studio' => 'visible',
        'label' => 'LBL_ESTATE_COMPANY',
        'id' => 'ACCOUNT_ID_C',
        'link' => true,
        'width' => '10%',
        'default' => false,
    ),
    'estate_contact' => array(
        'type' => 'relate',
        'studio' => 'visible',
        'label' => 'LBL_ESTATE_CONTACT',
        'id' => 'CONTACT_ID1_C',
        'link' => true,
        'width' => '10%',
        'default' => false,
    ),
    'contact_person' => array(
        'type' => 'relate',
        'studio' => 'visible',
        'label' => 'LBL_CONTACT_PERSON',
        'id' => 'CONTACT_ID_C',
        'link' => true,
        'width' => '10%',
        'default' => false,
    ),
    'occupant_type' => array(
        'type' => 'enum',
        'studio' => 'visible',
        'label' => 'LBL_OCCUPANT_TYPE',
        'width' => '10%',
        'default' => false,
    ),
    'status' => array(
        'type' => 'enum',
        'studio' => 'visible',
        'label' => 'LBL_STATUS',
        'width' => '10%',
        'default' => false,
    ),
    'ownership' => array(
        'type' => 'enum',
        'studio' => 'visible',
        'label' => 'LBL_OWNERSHIP',
        'width' => '10%',
        'default' => false,
    ),
    'address_notes' => array(
        'type' => 'text',
        'studio' => 'visible',
        'label' => 'LBL_ADDRESS_NOTES',
        'sortable' => false,
        'width' => '10%',
        'default' => false,
    ),
    'longitude' => array(
        'type' => 'float',
        'label' => 'LBL_LONGITUDE',
        'width' => '10%',
        'default' => false,
    ),
    'latitude' => array(
        'type' => 'float',
        'label' => 'LBL_LATITUDE',
        'width' => '10%',
        'default' => false,
    ),
    'address_location_link' => array(
        'type' => 'url',
        'label' => 'LBL_ADDRESS_LOCATION_LINK',
        'width' => '10%',
        'default' => false,
    ),
    'address_country' => array(
        'type' => 'varchar',
        'label' => 'LBL_ADDRESS_COUNTRY',
        'width' => '10%',
        'default' => false,
    ),
    'address_region' => array(
        'type' => 'enum',
        'studio' => 'visible',
        'label' => 'LBL_ADDRESS_REGION',
        'width' => '10%',
        'default' => false,
    ),
    'address_state' => array(
        'type' => 'enum',
        'studio' => 'visible',
        'label' => 'LBL_ADDRESS_STATE',
        'width' => '10%',
        'default' => false,
    ),
    'address_postalcode' => array(
        'type' => 'varchar',
        'label' => 'LBL_ADDRESS_POSTALCODE',
        'width' => '10%',
        'default' => false,
    ),
    'address_city' => array(
        'type' => 'varchar',
        'label' => 'LBL_ADDRESS_CITY',
        'width' => '10%',
        'default' => false,
    ),
    'address_street' => array(
        'type' => 'varchar',
        'label' => 'LBL_ADDRESS_STREET',
        'width' => '10%',
        'default' => false,
    ),
    'end_date' => array(
        'type' => 'date',
        'label' => 'LBL_END_DATE',
        'width' => '10%',
        'default' => false,
    ),
    'other' => array(
        'type' => 'varchar',
        'label' => 'LBL_OTHER',
        'width' => '10%',
        'default' => false,
    ),
    'description' => array(
        'type' => 'text',
        'label' => 'LBL_DESCRIPTION',
        'sortable' => false,
        'width' => '10%',
        'default' => false,
    ),
    'created_by_name' => array(
        'type' => 'relate',
        'link' => true,
        'label' => 'LBL_CREATED',
        'id' => 'CREATED_BY',
        'width' => '10%',
        'default' => false,
    ),
    'modified_by_name' => array(
        'type' => 'relate',
        'link' => true,
        'label' => 'LBL_MODIFIED_NAME',
        'id' => 'MODIFIED_USER_ID',
        'width' => '10%',
        'default' => false,
    ),
    'date_modified' => array(
        'width' => '15%',
        'label' => 'LBL_DATE_MODIFIED',
        'name' => 'date_modified',
        'default' => false,
    ),
    'created_by' => array(
        'width' => '8%',
        'label' => 'LBL_CREATED',
        'name' => 'created_by',
        'default' => false,
    ),
    'assigned_user_name' => array(
        'width' => '8%',
        'label' => 'LBL_LIST_ASSIGNED_USER',
        'name' => 'assigned_user_name',
        'default' => false,
    ),
);
