<?php
$module_name = 'stic_Assets';
$searchdefs[$module_name] =
array(
    'layout' => array(
        'basic_search' => array(
            'name' => array(
                'name' => 'name',
                'default' => true,
                'width' => '10%',
            ),
            'stic_assets_contacts_name' => array(
                'type' => 'relate',
                'link' => true,
                'label' => 'LBL_STIC_ASSETS_CONTACTS_FROM_CONTACTS_TITLE',
                'id' => 'STIC_ASSETS_CONTACTSCONTACTS_IDA',
                'width' => '10%',
                'default' => true,
                'name' => 'stic_assets_contacts_name',
            ),
            'code' => array(
                'type' => 'varchar',
                'label' => 'LBL_CODE',
                'width' => '10%',
                'default' => true,
                'name' => 'code',
            ),
            'type' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_TYPE',
                'width' => '10%',
                'default' => true,
                'name' => 'type',
            ),
            'start_date' => array(
                'type' => 'date',
                'label' => 'LBL_START_DATE',
                'width' => '10%',
                'default' => true,
                'name' => 'start_date',
            ),
            'assigned_user_id' => array(
                'name' => 'assigned_user_id',
                'label' => 'LBL_ASSIGNED_TO',
                'type' => 'enum',
                'function' => array(
                    'name' => 'get_user_array',
                    'params' => array(
                        0 => false,
                    ),
                ),
                'width' => '10%',
                'default' => true,
            ),
            'current_user_only' => array(
                'label' => 'LBL_CURRENT_USER_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
                'name' => 'current_user_only',
            ),
            'favorites_only' => array(
                'name' => 'favorites_only',
                'label' => 'LBL_FAVORITES_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
        ),
        'advanced_search' => array(
            'name' => array(
                'name' => 'name',
                'default' => true,
                'width' => '10%',
            ),
            'stic_assets_contacts_name' => array(
                'type' => 'relate',
                'link' => true,
                'label' => 'LBL_STIC_ASSETS_CONTACTS_FROM_CONTACTS_TITLE',
                'id' => 'STIC_ASSETS_CONTACTSCONTACTS_IDA',
                'width' => '10%',
                'default' => true,
                'name' => 'stic_assets_contacts_name',
            ),
            'code' => array(
                'type' => 'varchar',
                'label' => 'LBL_CODE',
                'width' => '10%',
                'default' => true,
                'name' => 'code',
            ),
            'type' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_TYPE',
                'width' => '10%',
                'default' => true,
                'name' => 'type',
            ),
            'other' => array(
                'type' => 'varchar',
                'label' => 'LBL_OTHER',
                'width' => '10%',
                'default' => true,
                'name' => 'other',
            ),
            'description' => array(
                'type' => 'text',
                'label' => 'LBL_DESCRIPTION',
                'sortable' => false,
                'width' => '10%',
                'default' => true,
                'name' => 'description',
            ),
            'start_date' => array(
                'type' => 'date',
                'label' => 'LBL_START_DATE',
                'width' => '10%',
                'default' => true,
                'name' => 'start_date',
            ),
            'end_date' => array(
                'type' => 'date',
                'label' => 'LBL_END_DATE',
                'width' => '10%',
                'default' => true,
                'name' => 'end_date',
            ),
            'address_street' => array(
                'type' => 'varchar',
                'label' => 'LBL_ADDRESS_STREET',
                'width' => '10%',
                'default' => true,
                'name' => 'address_street',
            ),
            'address_city' => array(
                'type' => 'varchar',
                'label' => 'LBL_ADDRESS_CITY',
                'width' => '10%',
                'default' => true,
                'name' => 'address_city',
            ),
            'address_postalcode' => array(
                'type' => 'varchar',
                'label' => 'LBL_ADDRESS_POSTALCODE',
                'width' => '10%',
                'default' => true,
                'name' => 'address_postalcode',
            ),
            'address_state' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_ADDRESS_STATE',
                'width' => '10%',
                'default' => true,
                'name' => 'address_state',
            ),
            'address_region' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_ADDRESS_REGION',
                'width' => '10%',
                'default' => true,
                'name' => 'address_region',
            ),
            'address_country' => array(
                'type' => 'varchar',
                'label' => 'LBL_ADDRESS_COUNTRY',
                'width' => '10%',
                'default' => true,
                'name' => 'address_country',
            ),
            'ownership' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_OWNERSHIP',
                'width' => '10%',
                'default' => true,
                'name' => 'ownership',
            ),
            'ownership_percentage' => array(
                'type' => 'int',
                'default' => true,
                'label' => 'LBL_OWNERSHIP_PERCENTAGE',
                'width' => '10%',
                'name' => 'ownership_percentage',
            ),
            'status' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_STATUS',
                'width' => '10%',
                'default' => true,
                'name' => 'status',
            ),
            'occupant_type' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_OCCUPANT_TYPE',
                'width' => '10%',
                'default' => true,
                'name' => 'occupant_type',
            ),
            'owners_president' => array(
                'type' => 'relate',
                'studio' => 'visible',
                'label' => 'LBL_OWNERS_PRESIDENT',
                'id' => 'CONTACT_ID2_C',
                'link' => true,
                'width' => '10%',
                'default' => true,
                'name' => 'owners_president',
            ),
            'estate_contact' => array(
                'type' => 'relate',
                'studio' => 'visible',
                'label' => 'LBL_ESTATE_CONTACT',
                'id' => 'CONTACT_ID1_C',
                'link' => true,
                'width' => '10%',
                'default' => true,
                'name' => 'estate_contact',
            ),
            'contact_person' => array(
                'type' => 'relate',
                'studio' => 'visible',
                'label' => 'LBL_CONTACT_PERSON',
                'id' => 'CONTACT_ID_C',
                'link' => true,
                'width' => '10%',
                'default' => true,
                'name' => 'contact_person',
            ),
            'key_set' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_KEY_SET',
                'width' => '10%',
                'default' => true,
                'name' => 'key_set',
            ),
            'estate_company' => array(
                'type' => 'relate',
                'studio' => 'visible',
                'label' => 'LBL_ESTATE_COMPANY',
                'id' => 'ACCOUNT_ID_C',
                'link' => true,
                'width' => '10%',
                'default' => true,
                'name' => 'estate_company',
            ),
            'insurance' => array(
                'type' => 'relate',
                'studio' => 'visible',
                'label' => 'LBL_INSURANCE',
                'id' => 'ACCOUNT_ID1_C',
                'link' => true,
                'width' => '10%',
                'default' => true,
                'name' => 'insurance',
            ),
            'policy_number' => array(
                'type' => 'varchar',
                'label' => 'LBL_POLICY_NUMBER',
                'width' => '10%',
                'default' => true,
                'name' => 'policy_number',
            ),
            'insured_building' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_INSURED_BUILDING',
                'width' => '10%',
                'default' => true,
                'name' => 'insured_building',
            ),
            'insured_contents' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_INSURED_CONTENTS',
                'width' => '10%',
                'default' => true,
                'name' => 'insured_contents',
            ),
            'electricity' => array(
                'type' => 'relate',
                'studio' => 'visible',
                'label' => 'LBL_ELECTRICITY',
                'id' => 'ACCOUNT_ID2_C',
                'link' => true,
                'width' => '10%',
                'default' => true,
                'name' => 'electricity',
            ),
            'gas' => array(
                'type' => 'relate',
                'studio' => 'visible',
                'label' => 'LBL_GAS',
                'id' => 'ACCOUNT_ID3_C',
                'link' => true,
                'width' => '10%',
                'default' => true,
                'name' => 'gas',
            ),
            'water' => array(
                'type' => 'relate',
                'studio' => 'visible',
                'label' => 'LBL_WATER',
                'id' => 'ACCOUNT_ID4_C',
                'link' => true,
                'width' => '10%',
                'default' => true,
                'name' => 'water',
            ),
            'phone' => array(
                'type' => 'relate',
                'studio' => 'visible',
                'label' => 'LBL_PHONE',
                'id' => 'ACCOUNT_ID5_C',
                'link' => true,
                'width' => '10%',
                'default' => true,
                'name' => 'phone',
            ),
            'security' => array(
                'type' => 'relate',
                'studio' => 'visible',
                'label' => 'LBL_SECURITY',
                'id' => 'ACCOUNT_ID6_C',
                'link' => true,
                'width' => '10%',
                'default' => true,
                'name' => 'security',
            ),
            'date_entered' => array(
                'type' => 'datetime',
                'label' => 'LBL_DATE_ENTERED',
                'width' => '10%',
                'default' => true,
                'name' => 'date_entered',
            ),
            'assigned_user_id' => array(
                'name' => 'assigned_user_id',
                'label' => 'LBL_ASSIGNED_TO',
                'type' => 'enum',
                'function' => array(
                    'name' => 'get_user_array',
                    'params' => array(
                        0 => false,
                    ),
                ),
                'width' => '10%',
                'default' => true,
            ),
            'date_modified' => array(
                'type' => 'datetime',
                'label' => 'LBL_DATE_MODIFIED',
                'width' => '10%',
                'default' => true,
                'name' => 'date_modified',
            ),
            'modified_user_id' => array(
                'type' => 'assigned_user_name',
                'label' => 'LBL_MODIFIED',
                'width' => '10%',
                'default' => true,
                'name' => 'modified_user_id',
            ),
            'created_by' => array(
                'type' => 'assigned_user_name',
                'label' => 'LBL_CREATED',
                'width' => '10%',
                'default' => true,
                'name' => 'created_by',
            ),
            'securitygroups_name' => array(
                'label' => 'LBL_SECURITYGROUPS_NAME',
                'width' => '10%',
                'default' => true,
                'type' => 'relate',
                'studio' => array(
                    'searchview' => true,
                    'visible' => false,
                ),
                'id' => '1',
                'link' => true,
                'name' => 'securitygroups_name',
            ),
            'current_user_only' => array(
                'label' => 'LBL_CURRENT_USER_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
                'name' => 'current_user_only',
            ),
            'favorites_only' => array(
                'name' => 'favorites_only',
                'label' => 'LBL_FAVORITES_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
        ),
    ),
    'templateMeta' => array(
        'maxColumns' => '3',
        'maxColumnsBasic' => '4',
        'widths' => array(
            'label' => '10',
            'field' => '30',
        ),
    ),
);
