-- Portal Authentication — Email Templates (English)
-- Updated: 2026-09-21 — only the email templates are shipped (REPLACE INTO, PK id).
--                     The PORTAL_TMPL_* references and the PORTAL_NOTIFY_* toggles are
--                     NOT seeded in `config`: they resolve to their system defaults
--                     (SticPortalConfigUtils::DEFAULTS) until an admin saves the portal
--                     configuration, which persists them as regular `config` rows.

-- Email Templates

REPLACE INTO email_templates (id, date_entered, date_modified, modified_user_id, created_by, published, name, description, subject, body, body_html, deleted, assigned_user_id, text_only, type) VALUES
('befd67fa-6017-11f1-8186-2299bea897ad',NOW(),NOW(),'1','1','yes','Example - Portal Credentials (Contacts)','Sent when a CRM user sends a portal invitation to a Contact','Your portal access credentials','Hello $contact_first_name,\n\nYour SinergiaCRM portal account has been created. This is your first time accessing it.\n\nFIRST STEP: Set your password before trying to sign in. Use this secure setup link to choose your password:\n$portal_reset_link\n\nAFTER SETTING YOUR PASSWORD:\nApplication: $portal_address\nPortal username: $contact_stic_portal_username_c\n\nThe password setup link expires in 24 hours. If you did not expect this invitation, contact your organization.','<p>Hello $contact_first_name,</p><p>Your SinergiaCRM portal account has been created. This is your first time accessing it.</p><p><strong>First step: Set your password before signing in.</strong> Use the secure setup link below to choose your password.</p><p><a href=\"$portal_reset_link\">Set Password</a></p><p><strong>After setting your password, sign in with:</strong></p><p>Application: <a href=\"$portal_address\">$portal_address</a><br>Portal username: $contact_stic_portal_username_c</p><p>The password setup link expires in 24 hours. If you did not expect this invitation, contact your organization.</p>',0,'1',0,'email'),
('befe7460-6017-11f1-8186-2299bea897ad',NOW(),NOW(),'1','1','yes','Example - Portal Credentials (Accounts)','Sent when a CRM user sends a portal invitation to an Account','Your portal access credentials','Hello,\n\nYour organization portal account has been created. This is your first time accessing it.\n\nFIRST STEP: Set your password before trying to sign in. Use this secure setup link to choose your password:\n$portal_reset_link\n\nAFTER SETTING YOUR PASSWORD:\nApplication: $portal_address\nPortal username: $account_stic_portal_username_c\n\nThe password setup link expires in 24 hours. If you did not expect this invitation, contact your organization.','<p>Hello,</p><p>Your organization portal account has been created. This is your first time accessing it.</p><p><strong>First step: Set your password before signing in.</strong> Use the secure setup link below to choose your password.</p><p><a href=\"$portal_reset_link\">Set Password</a></p><p><strong>After setting your password, sign in with:</strong></p><p>Application: <a href=\"$portal_address\">$portal_address</a><br>Portal username: $account_stic_portal_username_c</p><p>The password setup link expires in 24 hours. If you did not expect this invitation, contact your organization.</p>',0,'1',0,'email'),
('beff7975-6017-11f1-8186-2299bea897ad',NOW(),NOW(),'1','1','yes','Example - Portal Password Reset','Sent when a user requests a password reset','Password Reset Request','Hello,\n\nA password reset was requested. Click to reset (valid 1 hour): $portal_reset_link\n\nIgnore if not requested.','<p>Hello,</p><p>A password reset was requested. Click to reset (valid 1 hour): <a href=\"$portal_reset_link\">Reset Password</a></p><p>Ignore if not requested.</p>',0,'1',0,'email'),
('bf00573f-6017-11f1-8186-2299bea897ad',NOW(),NOW(),'1','1','yes','Example - Portal Magic Link','Sent when a user requests a magic link login','Your Login Link','Hello,\n\nClick to log in: $portal_magic_link\n\nIgnore if not requested.','<p>Hello,</p><p>Click to log in: <a href=\"$portal_magic_link\">Login to Portal</a></p><p>Ignore if not requested.</p>',0,'1',0,'email'),
('bf0102a9-6017-11f1-8186-2299bea897ad',NOW(),NOW(),'1','1','yes','Example - Portal Notification - Password Changed','Sent when a portal user changes their password','$portal_title - Your password was changed','Your portal password was changed at $notification_time from IP $notification_ip.\n\nContact support if not you.','<p>Your portal password was changed at $notification_time from IP $notification_ip.</p><p>Contact support if not you.</p>',0,'1',0,'email'),
('bf01ff0f-6017-11f1-8186-2299bea897ad',NOW(),NOW(),'1','1','yes','Example - Portal Notification - New Login','Sent when a new login is detected','$portal_title - New login detected','New login at $notification_time.\n\nIP: $notification_ip\nBrowser: $notification_ua\n\nContact support if not you.','<p>New login at $notification_time.</p><p>IP: $notification_ip</p><p>Browser: $notification_ua</p><p>Contact support if not you.</p>',0,'1',0,'email'),
('bf02dda3-6017-11f1-8186-2299bea897ad',NOW(),NOW(),'1','1','yes','Example - Portal Notification - Account Locked','Sent when portal account is locked','$portal_title - Account locked','Account locked due to failed attempts at $notification_time from IP $notification_ip.\n\nWill unlock automatically or contact support.','<p>Account locked due to failed attempts at $notification_time from IP $notification_ip.</p><p>Will unlock automatically or contact support.</p>',0,'1',0,'email'),
('bf03d86f-6017-11f1-8186-2299bea897ad',NOW(),NOW(),'1','1','yes','Example - Portal Notification - Reset Requested','Sent when password reset is requested','$portal_title - Password reset requested','Reset requested at $notification_time from IP $notification_ip.\n\nContact support if not you.','<p>Reset requested at $notification_time from IP $notification_ip.</p><p>Contact support if not you.</p>',0,'1',0,'email');

