SELECT
  id,
  name as name,
  assigned_user_id as assigned_user_id,
  modified_user_id as modified_user_id,
  created_by as created_by,
  date_entered as date_entered,
  date_modified as date_modified,
  deleted as deleted,
  description as description,
  tipo as type,
  estado as status,
  fechainicio as start_date,
  fechafin as end_date,
  informacionhorario as timetable,
  nombreubicacion as location,
  direccion as address,
  codigopostal as postal_code,
  provincia as state,
  comarca as county,
  municipio as city,
  comunidadautonoma as region,
  pais as country,
  motivodescarte as discard_reason,
  numeromaximo as max_attendees,
  numeroinscrinoinvitados as status_not_invited,
  numeroinscriinvitados as status_invited,
  numeroinscriconfirmados as status_confirmed,
  numeroinscrirechazados as status_rejected,
  numeroinscriquizas as status_maybe,
  numeroinscrinoparticipa as status_didnt_take_part,
  numeroinscriparticipa as status_took_part,
  presupuesto as budget,
  currency_id as currency_id,
  costeesperado as expected_cost,
  costereal as actual_cost,
  ingresosesperados as expected_income,
  ingresosreales as actual_income,
  importeasistencia as price,
  numeroinscriasistentesreal as attendees,
  total_hours as total_hours,
  numero_inscripciones_baja as status_drop_out
FROM
  redk_eventos
where
  deleted = 0;