<?php
$module_name = 'stic_Goals';
$searchdefs[$module_name] =
array(
    'layout' => array(
        'basic_search' => array(
            'name' => array(
                'name' => 'name',
                'default' => true,
                'width' => '10%',
            ),
            'stic_goals_contacts_name' => array(
                'type' => 'relate',
                'link' => true,
                'label' => 'LBL_STIC_GOALS_CONTACTS_FROM_CONTACTS_TITLE',
                'id' => 'STIC_GOALS_CONTACTSCONTACTS_IDA',
                'width' => '10%',
                'default' => true,
                'name' => 'stic_goals_contacts_name',
            ),
            'origin' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_ORIGIN',
                'width' => '10%',
                'default' => true,
                'name' => 'origin',
            ),
            'start_date' => array(
                'type' => 'date',
                'label' => 'LBL_START_DATE',
                'width' => '10%',
                'default' => true,
                'name' => 'start_date',
            ),
            'expected_end_date' => array(
                'type' => 'date',
                'label' => 'LBL_EXPECTED_END_DATE',
                'width' => '10%',
                'default' => true,
                'name' => 'expected_end_date',
            ),
            'actual_end_date' => array(
                'type' => 'date',
                'label' => 'LBL_ACTUAL_END_DATE',
                'width' => '10%',
                'default' => true,
                'name' => 'actual_end_date',
            ),
            'status' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_STATUS',
                'width' => '10%',
                'default' => true,
                'name' => 'status',
            ),
            'assigned_user_id' => array(
                'name' => 'assigned_user_id',
                'label' => 'LBL_ASSIGNED_TO',
                'type' => 'enum',
                'function' => array(
                    'name' => 'get_user_array',
                    'params' => array(
                        0 => false,
                    ),
                ),
                'width' => '10%',
                'default' => true,
            ),
            'current_user_only' => array(
                'name' => 'current_user_only',
                'label' => 'LBL_CURRENT_USER_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
            'favorites_only' => array(
                'name' => 'favorites_only',
                'label' => 'LBL_FAVORITES_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
        ),
        'advanced_search' => array(
            'name' => array(
                'name' => 'name',
                'default' => true,
                'width' => '10%',
            ),
            'stic_goals_contacts_name' => array(
                'type' => 'relate',
                'link' => true,
                'label' => 'LBL_STIC_GOALS_CONTACTS_FROM_CONTACTS_TITLE',
                'width' => '10%',
                'default' => true,
                'id' => 'STIC_GOALS_CONTACTSCONTACTS_IDA',
                'name' => 'stic_goals_contacts_name',
            ),
            'origin' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_ORIGIN',
                'width' => '10%',
                'default' => true,
                'name' => 'origin',
            ),
            'start_date' => array(
                'type' => 'date',
                'label' => 'LBL_START_DATE',
                'width' => '10%',
                'default' => true,
                'name' => 'start_date',
            ),
            'expected_end_date' => array(
                'type' => 'date',
                'label' => 'LBL_EXPECTED_END_DATE',
                'width' => '10%',
                'default' => true,
                'name' => 'expected_end_date',
            ),
            'actual_end_date' => array(
                'type' => 'date',
                'label' => 'LBL_ACTUAL_END_DATE',
                'width' => '10%',
                'default' => true,
                'name' => 'actual_end_date',
            ),
            'status' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_STATUS',
                'width' => '10%',
                'default' => true,
                'name' => 'status',
            ),
            'assigned_user_id' => array(
                'name' => 'assigned_user_id',
                'label' => 'LBL_ASSIGNED_TO',
                'type' => 'enum',
                'function' => array(
                    'name' => 'get_user_array',
                    'params' => array(
                        0 => false,
                    ),
                ),
                'width' => '10%',
                'default' => true,
            ),
            'area' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_AREA',
                'width' => '10%',
                'default' => true,
                'name' => 'area',
            ),
            'stic_goals_project_name' => array(
                'type' => 'relate',
                'link' => true,
                'label' => 'LBL_STIC_GOALS_PROJECT_FROM_PROJECT_TITLE',
                'id' => 'STIC_GOALS_PROJECTPROJECT_IDA',
                'width' => '10%',
                'default' => true,
                'name' => 'stic_goals_project_name',
            ),
            'stic_goals_stic_registrations_name' => array(
                'type' => 'relate',
                'link' => true,
                'label' => 'LBL_STIC_GOALS_STIC_REGISTRATIONS_FROM_STIC_REGISTRATIONS_TITLE',
                'id' => 'STIC_GOALS_STIC_REGISTRATIONSSTIC_REGISTRATIONS_IDA',
                'width' => '10%',
                'default' => true,
                'name' => 'stic_goals_stic_registrations_name',
            ),
            'stic_goals_stic_assessments_name' => array(
                'type' => 'relate',
                'link' => true,
                'label' => 'LBL_STIC_GOALS_STIC_ASSESSMENTS_FROM_STIC_ASSESSMENTS_TITLE',
                'id' => 'STIC_GOALS_STIC_ASSESSMENTSSTIC_ASSESSMENTS_IDA',
                'width' => '10%',
                'default' => true,
                'name' => 'stic_goals_stic_assessments_name',
            ),
            'subarea' => array(
                'type' => 'dynamicenum',
                'studio' => 'visible',
                'label' => 'LBL_SUBAREA',
                'width' => '10%',
                'default' => true,
                'name' => 'subarea',
            ),
            'area' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_AREA',
                'width' => '10%',
                'default' => false,
                'name' => 'area',
            ),

            'level' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_LEVEL',
                'width' => '10%',
                'default' => true,
                'name' => 'level',
            ),
            'created_by' => array(
                'type' => 'assigned_user_name',
                'label' => 'LBL_CREATED',
                'width' => '10%',
                'default' => true,
                'name' => 'created_by',
            ),
            'follow_up' => array(
                'type' => 'text',
                'studio' => 'visible',
                'label' => 'LBL_FOLLOW_UP',
                'sortable' => false,
                'width' => '10%',
                'default' => true,
                'name' => 'follow_up',
            ),
            'description' => array(
                'type' => 'text',
                'label' => 'LBL_DESCRIPTION',
                'sortable' => false,
                'width' => '10%',
                'default' => true,
                'name' => 'description',
            ),
            'date_entered' => array(
                'type' => 'datetime',
                'label' => 'LBL_DATE_ENTERED',
                'width' => '10%',
                'default' => true,
                'name' => 'date_entered',
            ),
            'modified_user_id' => array(
                'type' => 'assigned_user_name',
                'label' => 'LBL_MODIFIED',
                'width' => '10%',
                'default' => true,
                'name' => 'modified_user_id',
            ),
            'date_modified' => array(
                'type' => 'datetime',
                'label' => 'LBL_DATE_MODIFIED',
                'width' => '10%',
                'default' => true,
                'name' => 'date_modified',
            ),
            'current_user_only' => array(
                'label' => 'LBL_CURRENT_USER_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
                'name' => 'current_user_only',
            ),
            'favorites_only' => array(
                'name' => 'favorites_only',
                'label' => 'LBL_FAVORITES_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
        ),
    ),
    'templateMeta' => array(
        'maxColumns' => '3',
        'maxColumnsBasic' => '4',
        'widths' => array(
            'label' => '10',
            'field' => '30',
        ),
    ),
);

?>
