<?php
$module_name = 'stic_Resources';
$searchdefs[$module_name] =
array(
    'layout' => array(
        'basic_search' => array(
            'name' => array(
                'name' => 'name',
                'default' => true,
                'width' => '10%',
            ),
            'code' => array(
                'type' => 'varchar',
                'label' => 'LBL_CODE',
                'width' => '10%',
                'default' => true,
                'name' => 'code',
            ),
            'status' => array(
                'studio' => 'visible',
                'label' => 'LBL_STATUS',
                'width' => '10%',
                'default' => true,
                'name' => 'status',
            ),
            'type' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_TYPE',
                'width' => '10%',
                'default' => true,
                'name' => 'type',
            ),
            'color' => array(
                'type' => 'ColorPicker',
                'default' => true,
                'label' => 'LBL_COLOR',
                'width' => '10%',
                'name' => 'color',
            ),
            'hourly_rate' => array(
                'type' => 'decimal',
                'label' => 'LBL_HOURLY_RATE',
                'width' => '10%',
                'default' => true,
                'name' => 'hourly_rate',
            ),
            'daily_rate' => array(
                'type' => 'decimal',
                'label' => 'LBL_DAILY_RATE',
                'width' => '10%',
                'default' => true,
                'name' => 'daily_rate',
            ),
            'assigned_user_id' => array(
                'name' => 'assigned_user_id',
                'label' => 'LBL_ASSIGNED_TO',
                'type' => 'enum',
                'function' => array(
                    'name' => 'get_user_array',
                    'params' => array(
                        0 => false,
                    ),
                ),
                'width' => '10%',
                'default' => true,
            ),
            'current_user_only' => array(
                'name' => 'current_user_only',
                'label' => 'LBL_CURRENT_USER_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
            'favorites_only' => array(
                'name' => 'favorites_only',
                'label' => 'LBL_FAVORITES_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
        ),
        'advanced_search' => array(
            'name' => array(
                'name' => 'name',
                'default' => true,
                'width' => '10%',
            ),
            'code' => array(
                'type' => 'varchar',
                'label' => 'LBL_CODE',
                'width' => '10%',
                'default' => true,
                'name' => 'code',
            ),
            'status' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_STATUS',
                'width' => '10%',
                'default' => true,
                'name' => 'status',
            ),
            'type' => array(
                'type' => 'enum',
                'studio' => 'visible',
                'label' => 'LBL_TYPE',
                'width' => '10%',
                'default' => true,
                'name' => 'type',
            ),
            'color' => array(
                'type' => 'ColorPicker',
                'default' => true,
                'label' => 'LBL_COLOR',
                'width' => '10%',
                'name' => 'color',
            ),
            'hourly_rate' => array(
                'type' => 'decimal',
                'label' => 'LBL_HOURLY_RATE',
                'width' => '10%',
                'default' => true,
                'name' => 'hourly_rate',
            ),
            'daily_rate' => array(
                'type' => 'decimal',
                'label' => 'LBL_DAILY_RATE',
                'width' => '10%',
                'default' => true,
                'name' => 'daily_rate',
            ),
            'owner_contact' => array(
                'type' => 'relate',
                'studio' => 'visible',
                'label' => 'LBL_OWNER_CONTACT',
                'id' => 'CONTACT_ID_C',
                'link' => true,
                'width' => '10%',
                'default' => true,
                'name' => 'owner_contact',
            ),
            'owner_account' => array(
                'type' => 'relate',
                'studio' => 'visible',
                'label' => 'LBL_OWNER_ACCOUNT',
                'id' => 'ACCOUNT_ID_C',
                'link' => true,
                'width' => '10%',
                'default' => true,
                'name' => 'owner_account',
            ),
            'description' => array(
                'type' => 'text',
                'label' => 'LBL_DESCRIPTION',
                'sortable' => false,
                'width' => '10%',
                'default' => true,
                'name' => 'description',
            ),
            'created_by' => array(
                'type' => 'assigned_user_name',
                'label' => 'LBL_CREATED',
                'width' => '10%',
                'default' => true,
                'name' => 'created_by',
            ),
            'date_entered' => array(
                'type' => 'datetime',
                'label' => 'LBL_DATE_ENTERED',
                'width' => '10%',
                'default' => true,
                'name' => 'date_entered',
            ),
            'modified_user_id' => array(
                'type' => 'assigned_user_name',
                'label' => 'LBL_MODIFIED',
                'width' => '10%',
                'default' => true,
                'name' => 'modified_user_id',
            ),
            'date_modified' => array(
                'type' => 'datetime',
                'label' => 'LBL_DATE_MODIFIED',
                'width' => '10%',
                'default' => true,
                'name' => 'date_modified',
            ),
            'assigned_user_id' => array(
                'name' => 'assigned_user_id',
                'label' => 'LBL_ASSIGNED_TO',
                'type' => 'enum',
                'function' => array(
                    'name' => 'get_user_array',
                    'params' => array(
                        0 => false,
                    ),
                ),
                'default' => true,
                'width' => '10%',
            ),
            'current_user_only' => array(
                'label' => 'LBL_CURRENT_USER_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
                'name' => 'current_user_only',
            ),
            'favorites_only' => array(
                'name' => 'favorites_only',
                'label' => 'LBL_FAVORITES_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
        ),
    ),
    'templateMeta' => array(
        'maxColumns' => '3',
        'maxColumnsBasic' => '4',
        'widths' => array(
            'label' => '10',
            'field' => '30',
        ),
    ),
);
