<?php
$dictionary['adrep_column'] = array(
    'table' => 'adrep_column',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array (
  'report_id' => 
  array (
    'required' => false,
    'name' => 'report_id',
    'vname' => 'LBL_REPORT_NAME_ADREP_REPORT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'report_name' => 
  array (
    'required' => true,
    'source' => 'non-db',
    'name' => 'report_name',
    'vname' => 'LBL_REPORT_NAME',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Report this column is for.',
    'help' => 'Report this column is for.',
    'importable' => 'false',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'report_id',
    'ext2' => 'adrep_report',
    'module' => 'adrep_report',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'type' => 
  array (
    'required' => true,
    'name' => 'type',
    'vname' => 'LBL_TYPE',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'adrep_column_type_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'decimals' => 
  array (
    'required' => true,
    'name' => 'decimals',
    'vname' => 'LBL_DECIMALS',
    'type' => 'int',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => 'Number of decimals for number or currency column',
    'help' => 'Number of decimals for number or currency column',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '1',
    'min' => 0,
    'max' => 9,
    'validation' => 
    array (
      'type' => 'range',
      'min' => 0,
      'max' => 9,
    ),
  ),
  'dropdown_name' => 
  array (
    'required' => false,
    'name' => 'dropdown_name',
    'vname' => 'LBL_DROPDOWN_NAME',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'none',
    'no_default' => false,
    'comments' => 'Dropdown list to use for dropdown type column.',
    'help' => 'Dropdown list to use for dropdown type column.',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'adrep_dropdown_name_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'column_label' => 
  array (
    'required' => true,
    'name' => 'column_label',
    'vname' => 'LBL_PARAMETER_LABEL',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Column Label',
    'help' => 'Column Label',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '30',
    'size' => '20',
  ),
  'active_flag' => 
  array (
    'required' => false,
    'name' => 'active_flag',
    'vname' => 'LBL_ACTIVE_FLAG',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '1',
    'no_default' => false,
    'comments' => 'Show/Hide this column.',
    'help' => 'Show/Hide this column.',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'linked_module_name' => 
  array (
    'required' => false,
    'name' => 'linked_module_name',
    'vname' => 'LBL_LINKED_MODULE_NAME',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Module for Module Link type field.',
    'help' => 'Module for Module Link type field.',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'moduleList',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'name' => 
  array (
    'name' => 'name',
    'vname' => 'LBL_NAME',
    'type' => 'name',
    'link' => true,
    'dbType' => 'varchar',
    'len' => '30',
    'unified_search' => false,
    'full_text_search' => 
    array (
      'boost' => 3,
    ),
    'required' => true,
    'importable' => 'required',
    'duplicate_merge' => 'disabled',
    'merge_filter' => 'disabled',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'SQL result column name.',
    'help' => 'SQL result column name.',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'size' => '20',
  ),
  'description' => 
  array (
    'name' => 'description',
    'vname' => 'LBL_DESCRIPTION',
    'type' => 'text',
    'comment' => 'Full text of the note',
    'rows' => '6',
    'cols' => '80',
    'required' => false,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Description of the column',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
  ),
  'priority' => 
  array (
    'required' => true,
    'name' => 'priority',
    'vname' => 'LBL_PRIORITY',
    'type' => 'int',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => 'Position of the column',
    'help' => 'Position of the column',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '2',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '1',
    'min' => 0,
    'max' => 20,
    'validation' => 
    array (
      'type' => 'range',
      'min' => 0,
      'max' => 20,
    ),
  ),
  'total_type' => 
  array (
    'required' => false,
    'name' => 'total_type',
    'vname' => 'LBL_TOTAL_TYPE',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Type of column for summary/subtotal/total lines',
    'help' => 'Type of column for summary/subtotal/total lines',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'adrep_subtotal_type_list',
    'studio' => 'visible',
    'dependency' => false,
    'default' => 'blank',
  ),
  'width' => 
  array (
    'required' => true,
    'name' => 'width',
    'vname' => 'LBL_WIDTH',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'adrep_width_list',
    'studio' => 'visible',
    'dependency' => false,
    'default' => 'Auto',
  ),
),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('adrep_column', 'adrep_column', array('basic','assignable','security_groups'));
