-- Mail merge - Volunteer email merge templates
INSERT INTO dha_plantillasdocumentos (id, date_entered, date_modified, modified_user_id, created_by, description, deleted, assigned_user_id, document_name, filename, file_ext, file_mime_type, uploadfile, active_date, exp_date, category_id, subcategory_id, status_id, status, modulo, idioma, aclroles) VALUES 
('00000af4-deba-ddaf-949c-691b3d6e048a', NOW(), NOW(), '1', '1', NULL, 0, '1', 'SinergiaCRM - 01 - GV - ACUERDO DE INCORPORACIÓN', 'SinergiaCRM - 01 - GV - ACUERDO DE INCORPORACIÓN.docx', 'docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'SinergiaCRM - 01 - GV - ACUERDO DE INCORPORACIÓN.docx', '2025-11-17', NULL, NULL, NULL, 'Draft', 'Borrador', 'stic_Contacts_Relationships', 'es', '^^'),
('00000db5-1bd6-42ca-cefe-691f0af3575d', NOW(), NOW(), '1', '1', NULL, 0, '1', 'SinergiaCRM - 02 - GV - CARNÉ DE ACREDITACIÓN', 'SinergiaCRM - 02 - GV - CARNÉ DE ACREDITACIÓN.docx', 'docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'SinergiaCRM - 02 - GV - CARNÉ DE ACREDITACIÓN.docx', '2025-11-20', NULL, NULL, NULL, 'Draft', 'Borrador', 'stic_Contacts_Relationships', 'es', '^^'),
('00000983-1596-2aee-74ca-692720697fe2', NOW(), NOW(), '1', '1', NULL, 0, '1', 'SinergiaCRM - 03A - GV - CERTIFICADO DE PARTICIPACIÓN (RELACIÓN)', 'SinergiaCRM - 03A - GV - CERTIFICADO DE PARTICIPACIÓN (RELACIÓN).docx', 'docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'SinergiaCRM - 03A - GV - CERTIFICADO DE PARTICIPACIÓN (RELACIÓN).docx', '2025-11-26', NULL, NULL, NULL, 'Draft', 'Borrador', 'stic_Contacts_Relationships', 'es', '^^'),
('00000b83-5f17-66f7-6f8f-69271fbb5939', NOW(), NOW(), '1', '1', NULL, 0, '1', 'SinergiaCRM - 03B - GV - CERTIFICADO DE PARTICIPACIÓN EN ACTIVIDADES (HISTÓRICO)', 'SinergiaCRM - 03B - GV - CERTIFICADO DE PARTICIPACIÓN EN ACTIVIDADES (HISTÓRICO).docx', 'docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'SinergiaCRM - 03B - GV - CERTIFICADO DE PARTICIPACIÓN EN ACTIVIDADES (HISTÓRICO).docx', '2025-11-26', NULL, NULL, NULL, 'Draft', 'Borrador', 'Contacts', 'es', '^^'),
('000009ae-9215-baaa-33f2-6927255adb75', NOW(), NOW(), '1', '1', NULL, 0, '1', 'SinergiaCRM - 03C - GV - CERTIFICADO DE PARTICIPACIÓN (INSCRIPCIÓN)', 'SinergiaCRM - 03C - GV - CERTIFICADO DE PARTICIPACIÓN (INSCRIPCIÓN).docx', 'docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'SinergiaCRM - 03C - GV - CERTIFICADO DE PARTICIPACIÓN (INSCRIPCIÓN).docx', '2025-11-26', NULL, NULL, NULL, 'Draft', 'Borrador', 'stic_Registrations', 'es', '^^'),
('00000648-2df0-6bb5-ade6-69272affbda2', NOW(), NOW(), '1', '1', NULL, 0, '1', 'SinergiaCRM - 04 - GV - CERTIFICADO DE RECONOCIMIENTO DE COMPETENCIAS', 'SinergiaCRM - 04 - GV - CERTIFICADO DE RECONOCIMIENTO DE COMPETENCIAS.docx', 'docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'SinergiaCRM - 04 - GV - CERTIFICADO DE RECONOCIMIENTO DE COMPETENCIAS.docx', '2025-11-26', NULL, NULL, NULL, 'Draft', 'Borrador', 'Contacts', 'es', '^^'),
('00000500-d93a-f264-e01b-691f40d648f1', NOW(), NOW(), '1', '1', NULL, 0, '1', 'SinergiaCRM - 05 - GV - AUTORIZACIÓN PADRE_MADRE_TUTOR', 'SinergiaCRM - 05 - GV - AUTORIZACIÓN PADRE_MADRE_TUTOR.docx', 'docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'SinergiaCRM - 05 - GV - AUTORIZACIÓN PADRE_MADRE_TUTOR.docx', '2025-11-20', NULL, NULL, NULL, 'Draft', 'Borrador', 'stic_Personal_Environment', 'es', '^^'),
('000000a5-cc6f-7c9a-72e0-6926dfdec055', NOW(), NOW(), '1', '1', NULL, 0, '1', 'SinergiaCRM - 06 - GV - BAJA DE LA PERSONA VOLUNTARIA', 'SinergiaCRM - 06 - GV - BAJA DE LA PERSONA VOLUNTARIA.docx', 'docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'SinergiaCRM - 06 - GV - BAJA DE LA PERSONA VOLUNTARIA.docx', '2025-11-26', NULL, NULL, NULL, 'Draft', 'Borrador', 'Contacts', 'es', '^^'),
('00000e43-2e4c-63f4-ec24-6929d5aa8ee3', NOW(), NOW(), '1', '1', NULL, 0, '1', 'SinergiaCRM - 07 - GV - CARTA DE AGRADECIMIENTO', 'SinergiaCRM - 07 - GV - CARTA DE AGRADECIMIENTO.docx', 'docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'SinergiaCRM - 07 - GV - CARTA DE AGRADECIMIENTO.docx', '2025-11-28', NULL, NULL, NULL, 'Draft', 'Borrador', 'Contacts', 'es', '^^');
