<?php
/**
 * This file is part of SinergiaCRM.
 * SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
 * Copyright (C) 2013 - 2023 SinergiaTIC Association
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
 */

$dictionary['stic_Allocations'] = array(
    'table' => 'stic_allocations',
    'audited' => 1,
    'inline_edit' => 1,
    'duplicate_merge' => 1,
    'fields' => array(
        'validated' => array(
            'required' => 0,
            'name' => 'validated',
            'vname' => 'LBL_VALIDATED',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'bool',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'inline_edit' => 1,
            'default' => '0',
        ),
        'blocked' => array(
            'required' => 0,
            'name' => 'blocked',
            'vname' => 'LBL_BLOCKED',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'bool',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'inline_edit' => 1,
            'default' => '0',
        ),
        'type' => array(
            'required' => 1,
            'name' => 'type',
            'vname' => 'LBL_TYPE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'enum',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 100,
            'size' => '20',
            'options' => 'stic_allocations_types_list',
            'studio' => 'visible',
            'dependency' => 0,
            'inline_edit' => 1,
        ),
        'date' => array(
            'required' => 1,
            'name' => 'date',
            'vname' => 'LBL_DATE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'date',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'inline_edit' => 1,
        ),
        'payment_amount_field' => array(
            'required' => 1,
            'name' => 'payment_amount_field',
            'vname' => 'LBL_PAYMENT_AMOUNT_FIELD',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'enum',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 100,
            'size' => '20',
            'options' => 'stic_allocations_amount_fields_list',
            'studio' => 'visible',
            'dependency' => 0,
            'inline_edit' => 1,
        ),
        'percentage' => array(
            'required' => true,
            'name' => 'percentage',
            'vname' => 'LBL_PERCENTAGE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'decimal',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 5,
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'precision' => 2,
            'inline_edit' => 1,
        ),
        'amount' => array(
            'required' => 0,
            'name' => 'amount',
            'vname' => 'LBL_AMOUNT',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'decimal',
            'massupdate' => 0,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 26,
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'precision' => 2,
            'inline_edit' => 0,
        ),
        'hours' => array(
            'required' => 0,
            'name' => 'hours',
            'vname' => 'LBL_HOURS',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'int',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 11,
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'inline_edit' => 1,
        ),
        'stic_allocation_proposals' => array(
            'name' => 'stic_allocation_proposals',
            'type' => 'link',
            'relationship' => 'stic_allocation_proposals_stic_allocations',
            'source' => 'non-db',
            'module' => 'stic_Allocation_Proposals',
            'bean_name' => 'stic_Allocation_Proposals',
            'vname' => 'LBL_STIC_ALLOCATION_PROPOSALS_STIC_ALLOCATIONS_FROM_STIC_ALLOCATIONS_TITLE',
            'id_name' => 'stic_allocation_propo424d',
        ),
        'stic_allocation_proposals_name' => array(
            'name' => 'stic_allocation_proposals_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_ALLOCATION_PROPOSALS_STIC_ALLOCATIONS_FROM_STIC_ALLOCATIONS_TITLE',
            'save' => true,
            'required' => true,
            'importable' => 'required',
            'id_name' => 'stic_allocation_propo424d',
            'link' => 'stic_allocation_proposals',
            'table' => 'stic_allocation_proposals',
            'module' => 'stic_Allocation_Proposals',
            'rname' => 'name',
            'inline_edit' => 1,
            'massupdate' => 0,
        ),
        'stic_allocation_propo424d' => array(
            'name' => 'stic_allocation_propo424d',
            'type' => 'link',
            'relationship' => 'stic_allocation_proposals_stic_allocations',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_ALLOCATION_PROPOSALS_STIC_ALLOCATIONS_FROM_STIC_ALLOCATION_PROPOSALS_TITLE',
        ),
        'stic_payments' => array(
            'name' => 'stic_payments',
            'type' => 'link',
            'relationship' => 'stic_payments_stic_allocations',
            'source' => 'non-db',
            'module' => 'stic_Payments',
            'bean_name' => 'stic_Payments',
            'vname' => 'LBL_STIC_PAYMENTS_STIC_ALLOCATIONS_FROM_STIC_ALLOCATIONS_TITLE',
            'id_name' => 'stic_payments_stic_aleb9a',
        ),
        'stic_payments_name' => array(
            'name' => 'stic_payments_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_PAYMENTS_STIC_ALLOCATIONS_FROM_STIC_ALLOCATIONS_TITLE',
            'save' => true,
            'required' => true,
            'importable' => 'required',
            'id_name' => 'stic_payments_stic_aleb9a',
            'link' => 'stic_payments',
            'table' => 'stic_payments',
            'module' => 'stic_Payments',
            'rname' => 'name',
            'inline_edit' => 1,
            'massupdate' => 0,
        ),
        'stic_payments_stic_aleb9a' => array(
            'name' => 'stic_payments_stic_aleb9a',
            'type' => 'link',
            'relationship' => 'stic_payments_stic_allocations',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_PAYMENTS_STIC_ALLOCATIONS_FROM_STIC_PAYMENTS_TITLE',
        ),
        'stic_ledger_accounts_name' => array(
            'required' => true,
            'source' => 'non-db',
            'name' => 'stic_ledger_accounts_name',
            'vname' => 'LBL_STIC_LEDGER_ACCOUNTS',
            'type' => 'relate',
            'massupdate' => 1,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'stic_ledger_accounts_ida',
            'ext2' => 'stic_Ledger_Accounts',
            'module' => 'stic_Ledger_Accounts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'stic_ledger_accounts_ida' => array(
            'name' => 'stic_ledger_accounts_ida',
            'type' => 'id',
            'source' => 'db',
            'vname' => 'LBL_STIC_LEDGER_ACCOUNTS_ID',
            'reportable' => false,
        ),
        'stic_allocations_stic_justifications' => array(
            'name' => 'stic_allocations_stic_justifications',
            'type' => 'link',
            'relationship' => 'stic_allocations_stic_justifications',
            'source' => 'non-db',
            'module' => 'stic_Justifications',
            'bean_name' => 'stic_Justifications',
            'side' => 'left',
            'vname' => 'LBL_STIC_ALLOCATIONS_STIC_JUSTIFICATIONS_FROM_STIC_JUSTIFICATIONS_TITLE',
        ),
        'opportunities_stic_allocations' => array(
            'name' => 'opportunities_stic_allocations',
            'type' => 'link',
            'relationship' => 'opportunities_stic_allocations',
            'source' => 'non-db',
            'module' => 'Opportunities',
            'bean_name' => 'Opportunity',
            'vname' => 'LBL_OPPORTUNITIES_STIC_ALLOCATIONS_FROM_OPPORTUNITIES_TITLE',
            'id_name' => 'opportunities_stic_allocationsopportunities_ida',
        ),
        'opportunities_stic_allocations_name' => array(
            'name' => 'opportunities_stic_allocations_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_OPPORTUNITIES_STIC_ALLOCATIONS_FROM_OPPORTUNITIES_TITLE',
            'save' => true,
            'required' => false,
            'importable' => 'true',
            'id_name' => 'opportunities_stic_allocationsopportunities_ida',
            'link' => 'opportunities_stic_allocations',
            'table' => 'opportunities',
            'module' => 'Opportunities',
            'rname' => 'name',
            'inline_edit' => 1,
            'massupdate' => 0,
        ),
        'opportunities_stic_allocationsopportunities_ida' => array(
            'name' => 'opportunities_stic_allocationsopportunities_ida',
            'type' => 'link',
            'relationship' => 'opportunities_stic_allocations',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_OPPORTUNITIES_STIC_ALLOCATIONS_FROM_OPPORTUNITIES_TITLE',
        ),
        'project_stic_allocations' => array(
            'name' => 'project_stic_allocations',
            'type' => 'link',
            'relationship' => 'project_stic_allocations',
            'source' => 'non-db',
            'module' => 'Project',
            'bean_name' => 'Project',
            'vname' => 'LBL_PROJECT_STIC_ALLOCATIONS_FROM_PROJECT_TITLE',
            'id_name' => 'project_stic_allocationsproject_ida',
        ),
        'project_stic_allocations_name' => array(
            'name' => 'project_stic_allocations_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_PROJECT_STIC_ALLOCATIONS_FROM_PROJECT_TITLE',
            'save' => true,
            'required' => true,
            'importable' => 'true',
            'id_name' => 'project_stic_allocationsproject_ida',
            'link' => 'project_stic_allocations',
            'table' => 'project',
            'module' => 'Project',
            'rname' => 'name',
            'inline_edit' => 1,
            'massupdate' => 0,
        ),
        'project_stic_allocationsproject_ida' => array(
            'name' => 'project_stic_allocationsproject_ida',
            'type' => 'link',
            'relationship' => 'project_stic_allocations',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_PROJECT_STIC_ALLOCATIONS_FROM_PROJECT_TITLE',
        ),
    ),
    'indices' => array(
    ),
    'relationships' => array(

    ),
    'optimistic_locking' => 1,
    'unified_search' => true,
    'unified_search_default_enabled' => true,
);
if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('stic_Allocations', 'stic_Allocations', array('basic', 'assignable', 'security_groups'));

// Set special values for SuiteCRM base fields
$dictionary['stic_Allocations']['fields']['name']['required'] = '0'; // Name is required in this module
$dictionary['stic_Allocations']['fields']['name']['importable'] = 'true'; // Name is required for import
$dictionary['stic_Allocations']['fields']['name']['audited'] = 1;
$dictionary['stic_Allocations']['fields']['description']['rows'] = '2'; // Make textarea fields shorter