<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2019 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

$mod_strings = array(
    'DEFAULT_CHARSET' => '',
    'LBL_DISABLED_TITLE' => '',
    'LBL_DISABLED_TITLE_2' => '',
    'LBL_DISABLED_DESCRIPTION' => '',
    'LBL_DISABLED_DESCRIPTION_2' => '',
    'LBL_DISABLED_HELP_1' => '',
    'LBL_DISABLED_HELP_2' => '',

    'LBL_REG_TITLE' => '',
    'LBL_REG_CONF_1' => '',
    'LBL_REG_CONF_2' => '',
    'LBL_REG_CONF_3' => '',


    'ERR_ADMIN_PASS_BLANK' => '',
    'ERR_CHECKSYS_CALL_TIME' => '',
    'ERR_CHECKSYS_CURL' => '',
    'ERR_CHECKSYS_MEM_LIMIT_1' => '',
    'ERR_CHECKSYS_MEM_LIMIT_2' => '',
    'ERR_CHECKSYS_NO_SESSIONS' => '',
    'ERR_CHECKSYS_NOT_VALID_DIR' => '',
    'ERR_CHECKSYS_NOT_WRITABLE' => '',
    'ERR_CHECKSYS_PHP_INVALID_VER' => '',
    'ERR_CHECKSYS_PHP_UNSUPPORTED' => '',
    'ERR_CHECKSYS_SAFE_MODE' => '',
    'ERR_DB_ADMIN' => '',
    'ERR_DB_EXISTS_NOT' => '',
    'ERR_DB_EXISTS_WITH_CONFIG' => '',
    'ERR_DB_EXISTS' => '',
    'ERR_DB_HOSTNAME' => '',
    'ERR_DB_INVALID' => '',
    'ERR_DB_LOGIN_FAILURE_MYSQL' => '',
    'ERR_DB_MYSQL_VERSION1' => '',
    'ERR_DB_MYSQL_VERSION2' => '',
    'ERR_DB_NAME' => '',
    'ERR_DB_NAME2' => "",
    'ERR_DB_PASSWORD' => '',
    'ERR_DB_PRIV_USER' => '',
    'ERR_DB_USER_EXISTS' => '',
    'ERR_DB_USER' => '',
    'ERR_DBCONF_VALIDATION' => '',
    'ERR_ERROR_GENERAL' => '',
    'ERR_LICENSE_MISSING' => '',
    'ERR_LICENSE_NOT_FOUND' => '',
    'ERR_LOG_DIRECTORY_NOT_EXISTS' => '',
    'ERR_LOG_DIRECTORY_NOT_WRITABLE' => '',
    'ERR_LOG_DIRECTORY_REQUIRED' => '',
    'ERR_NO_DIRECT_SCRIPT' => '',
    'ERR_PASSWORD_MISMATCH' => '',
    'ERR_PERFORM_CONFIG_PHP_1' => '',
    'ERR_PERFORM_CONFIG_PHP_2' => '',
    'ERR_PERFORM_CONFIG_PHP_3' => '',
    'ERR_PERFORM_CONFIG_PHP_4' => '',
    'ERR_PERFORM_HTACCESS_1' => '',
    'ERR_PERFORM_HTACCESS_2' => '',
    'ERR_PERFORM_HTACCESS_3' => '',
    'ERR_PERFORM_NO_TCPIP' => '',
    'ERR_SESSION_DIRECTORY_NOT_EXISTS' => '',
    'ERR_SESSION_DIRECTORY' => '',
    'ERR_SESSION_PATH' => '',
    'ERR_SI_NO_CONFIG' => '',
    'ERR_SITE_GUID' => '',
    'ERR_URL_BLANK' => '',
    'LBL_BACK' => '',
    'LBL_CHECKSYS_1' => '',
    'LBL_CHECKSYS_CACHE' => '',
    'LBL_CHECKSYS_CALL_TIME' => '',
    'LBL_CHECKSYS_COMPONENT' => '',
    'LBL_CHECKSYS_CONFIG' => '',
    'LBL_CHECKSYS_CURL' => '',
    'LBL_CHECKSYS_CUSTOM' => '',
    'LBL_CHECKSYS_DATA' => '',
    'LBL_CHECKSYS_MEM_OK' => '',
    'LBL_CHECKSYS_MEM_UNLIMITED' => '',
    'LBL_CHECKSYS_MEM' => '',
    'LBL_CHECKSYS_MODULE' => '',
    'LBL_CHECKSYS_NOT_AVAILABLE' => '',
    'LBL_CHECKSYS_OK' => '',
    'LBL_CHECKSYS_PHP_INI' => '',
    'LBL_CHECKSYS_PHP_OK' => '',
    'LBL_CHECKSYS_PHPVER' => '',
    'LBL_CHECKSYS_RECHECK' => '',
    'LBL_CHECKSYS_SAFE_MODE' => '',
    'LBL_CHECKSYS_SESSION' => '',
    'LBL_CHECKSYS_STATUS' => '',
    'LBL_CHECKSYS_TITLE' => '',
    'LBL_CHECKSYS_XML' => '',
    'LBL_CLOSE' => '',
    'LBL_CONFIRM_BE_CREATED' => '',
    'LBL_CONFIRM_DB_TYPE' => '',
    'LBL_CONFIRM_DIRECTIONS' => '',
    'LBL_CONFIRM_LICENSE_TITLE' => '',
    'LBL_CONFIRM_NOT' => '',
    'LBL_CONFIRM_TITLE' => '',
    'LBL_CONFIRM_WILL' => '',
    'LBL_DBCONF_CREATE_DB' => '',
    'LBL_DBCONF_CREATE_USER' => '',
    'LBL_DBCONF_DB_DROP_CREATE_WARN' => '',
    'LBL_DBCONF_DB_DROP_CREATE' => '',
    'LBL_DBCONF_DB_NAME' => '',
    'LBL_DBCONF_DB_PASSWORD' => '',
    'LBL_DBCONF_DB_PASSWORD2' => '',
    'LBL_DBCONF_DB_USER' => '',
    'LBL_DBCONF_DEMO_DATA' => '',
    'LBL_DBCONF_HOST_NAME' => '',
    'LBL_DBCONF_INSTRUCTIONS' => '',
    'LBL_DBCONF_MB_DEMO_DATA' => '',
    'LBL_DBCONF_PRIV_PASS' => '',
    'LBL_DBCONF_PRIV_USER_2' => '',
    'LBL_DBCONF_PRIV_USER_DIRECTIONS' => '',
    'LBL_DBCONF_PRIV_USER' => '',
    'LBL_DBCONF_TITLE' => '',
    'LBL_HELP' => '',
    'LBL_LICENSE_ACCEPTANCE' => '',
    'LBL_LICENSE_DIRECTIONS' => '',
    'LBL_LICENSE_DOWNLOAD_KEY' => '',
    'LBL_LICENSE_EXPIRY' => '',
    'LBL_LICENSE_I_ACCEPT' => '',
    'LBL_LICENSE_NUM_USERS' => '',
    'LBL_LICENSE_OC_DIRECTIONS' => '',
    'LBL_LICENSE_OC_NUM' => '',
    'LBL_LICENSE_OC' => '',
    'LBL_LICENSE_PRINTABLE' => '',
    'LBL_LICENSE_TITLE' => '',
    'LBL_LICENSE_TITLE_2' => '',
    'LBL_LICENSE_USERS' => '',
    'LBL_MYSQL' => '',
    'LBL_NEXT' => '',
    'LBL_NO' => '',
    'LBL_ORACLE' => '',
    'LBL_PERFORM_ADMIN_PASSWORD' => '',
    'LBL_PERFORM_AUDIT_TABLE' => '',
    'LBL_PERFORM_CONFIG_PHP' => '',
    'LBL_PERFORM_CREATE_DB_1' => '',
    'LBL_PERFORM_CREATE_DB_2' => '',
    'LBL_PERFORM_CREATE_DB_USER' => '',
    'LBL_PERFORM_CREATE_DEFAULT' => '',
    'LBL_PERFORM_CREATE_LOCALHOST' => '',
    'LBL_PERFORM_CREATE_RELATIONSHIPS' => '',
    'LBL_PERFORM_CREATING' => '',
    'LBL_PERFORM_DEFAULT_REPORTS' => '',
    'LBL_PERFORM_DEFAULT_SCHEDULER' => '',
    'LBL_PERFORM_DEFAULT_SETTINGS' => '',
    'LBL_PERFORM_DEFAULT_USERS' => '',
    'LBL_PERFORM_DEMO_DATA' => '',
    'LBL_PERFORM_DONE' => '',
    'LBL_PERFORM_DROPPING' => '',
    'LBL_PERFORM_FINISH' => '',
    'LBL_PERFORM_LICENSE_SETTINGS' => '',
    'LBL_PERFORM_OUTRO_1' => '',
    'LBL_PERFORM_OUTRO_2' => '',
    'LBL_PERFORM_OUTRO_3' => '',
    'LBL_PERFORM_OUTRO_4' => '',
    'LBL_PERFORM_OUTRO_5' => '',
    'LBL_PERFORM_OUTRO_6' => '',
    'LBL_PERFORM_OUTRO_7' => '',
    'LBL_PERFORM_REL_META' => '',
    'LBL_PERFORM_SUCCESS' => '',
    'LBL_PERFORM_TABLES' => '',
    'LBL_PERFORM_TITLE' => '',
    'LBL_PRINT' => '',
    'LBL_REQUIRED' => '',
    'LBL_SITECFG_ADMIN_PASS_2' => '',
    'LBL_SITECFG_ADMIN_PASS_WARN' => '',
    'LBL_SITECFG_ADMIN_PASS' => '',
    'LBL_SITECFG_APP_ID' => '',
    'LBL_SITECFG_CUSTOM_ID_DIRECTIONS' => '',
    'LBL_SITECFG_CUSTOM_ID' => '',
    'LBL_SITECFG_CUSTOM_LOG_DIRECTIONS' => '',
    'LBL_SITECFG_CUSTOM_LOG' => '',
    'LBL_SITECFG_CUSTOM_SESSION_DIRECTIONS' => '',
    'LBL_SITECFG_CUSTOM_SESSION' => '',
    'LBL_SITECFG_DIRECTIONS' => '',
    'LBL_SITECFG_FIX_ERRORS' => '',
    'LBL_SITECFG_LOG_DIR' => '',
    'LBL_SITECFG_SESSION_PATH' => '',
    'LBL_SITECFG_SITE_SECURITY' => '',
    'LBL_SITECFG_SUGAR_UP_DIRECTIONS' => '',
    'LBL_SITECFG_SUGAR_UP' => '',
    'LBL_SITECFG_SUGAR_UPDATES' => '',
    'LBL_SITECFG_TITLE' => '',
    'LBL_SITECFG_URL' => '',
    'LBL_SITECFG_USE_DEFAULTS' => '',
    'LBL_START' => '',
    'LBL_STEP' => '',
    'LBL_TITLE_WELCOME' => '',
    'LBL_WELCOME_1' => '',
    'LBL_WELCOME_2' => '',
    'LBL_WELCOME_CHOOSE_LANGUAGE' => '',
    'LBL_WELCOME_SETUP_WIZARD' => '',
    'LBL_WELCOME_TITLE_WELCOME' => '',
    'LBL_WELCOME_TITLE' => '',
    'LBL_WIZARD_TITLE' => '',
    'LBL_YES' => '',
);
