<?php
/*
 * The MIT License (MIT)
 * 
 * Copyright (c) 2018 Marnus van Niekerk, crm@mjvn.net
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

$dictionary['adrep_schedule'] = array(
    'table' => 'adrep_schedule',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array (
  'query' =>
  array (
    'required' => true,
    'name' => 'query',
    'vname' => 'LBL_QUERY',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Query that will return the email addresses and parameters for the report',
    'help' => 'Query that will return the email addresses and parameters for the report',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'email_column' =>
  array (
    'required' => true,
    'name' => 'email_column',
    'vname' => 'LBL_EMAIL_COLUMN',
    'type' => 'varchar',
    'massupdate' => 0,
    'default' => 'email_address',
    'no_default' => false,
    'comments' => 'Column from query that contain the email address(es)',
    'help' => 'Column from query that contain the email address(es)',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '50',
    'size' => '20',
  ),
  'report_id' =>
  array (
    'required' => false,
    'name' => 'report_id',
    'vname' => 'LBL_REPORT_NAME_ADREP_REPORT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'report_name' =>
  array (
    'required' => true,
    'source' => 'non-db',
    'name' => 'report_name',
    'vname' => 'LBL_REPORT_NAME',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Report to run',
    'help' => 'Report to run',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'report_id',
    'ext2' => 'adrep_report',
    'module' => 'adrep_report',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'format' =>
  array (
    'required' => true,
    'name' => 'format',
    'vname' => 'LBL_FORMAT',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'html',
    'no_default' => false,
    'comments' => 'Format to attach',
    'help' => 'Format to attach',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'adrep_email_format_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'dow' =>
  array (
    'required' => true,
    'name' => 'dow',
    'vname' => 'LBL_DOW',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Day of week for report',
    'help' => 'Day of week for report',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'adrep_dow_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
	'dom' =>
    array (
      'inline_edit' => '1',
      'labelValue' => 'Day of Month',
      'required' => false,
      'name' => 'dom',
      'vname' => 'LBL_TEST',
      'type' => 'multienum',
      'massupdate' => '0',
      'default' => '[All]',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'options' => 'adrep_dom_list',
      'studio' => 'visible',
      'isMultiSelect' => true,
      'id' => 'adrep_scheduletest_c',
      'custom_module' => 'adrep_schedule',
    ),
  'tod' =>
  array (
    'required' => true,
    'name' => 'tod',
    'vname' => 'LBL_TOD',
    'type' => 'varchar',
    'massupdate' => 0,
    'default' => '00:00',
    'no_default' => false,
    'comments' => 'Time of day for report',
    'help' => 'Time of day for report',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '5',
    'size' => '20',
  ),
  'active_flag' =>
  array (
    'required' => false,
    'name' => 'active_flag',
    'vname' => 'LBL_ACTIVE_FLAG',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('adrep_schedule', 'adrep_schedule', array('basic','assignable','security_groups'));
